"""
Stopwords Corpus

This corpus contains lists of stop words for several languages.  These
are high-frequency grammatical words which are usually ignored in text
retrieval applications.

The above description and below words comes from NLTK project:
https://www.nltk.org/
"""

__all__ = ['get_words']


_words = {
    'arabic': {'حاشا', 'لم', 'إذن', 'أنتما', 'ذو', 'كلاهما', 'ته', 'في', 'لكن',
               'سوى', 'ليست', 'هاهنا', 'ذلكما', 'إليكن', 'تي', 'فيه', 'إذ',
               'غير', 'إذا', 'كل', 'كم', 'أنا', 'هو', 'على', 'هناك', 'هن',
               'وإن', 'لا', 'نعم', 'بماذا', 'هم', 'ذان', 'أما', 'هاتان', 'أم',
               'آي', 'عما', 'لوما', 'ذواتي', 'لسن', 'إيه', 'ثم', 'إذما',
               'لكيلا', 'أيها', 'هاك', 'دون', 'كيفما', 'عند', 'ذانك', 'لكم',
               'منه', 'هذه', 'هذا', 'هيت', 'لها', 'هؤلاء', 'بكم', 'أنى', 'لما',
               'ذين', 'لكما', 'نحن', 'بس', 'بنا', 'إلى', 'لي', 'هلا', 'ثمة',
               'لئن', 'ليت', 'منها', 'والذين', 'كما', 'بيد', 'فإذا', 'حين',
               'وإذ', 'إن', 'فلا', 'ذينك', 'ولكن', 'هي', 'بخ', 'عن', 'خلا',
               'هما', 'شتان', 'أنتن', 'نحو', 'لهن', 'لسنا', 'لدى', 'متى', 'يا',
               'تينك', 'حتى', 'اللتيا', 'لهما', 'إلا', 'ولو', 'لنا', 'ذلكم',
               'وهو', 'لن', 'إنا', 'ممن', 'عل', 'بعد', 'أولئك', 'تلكما', 'قد',
               'بك', 'بما', 'اللتان', 'فمن', 'كذلك', 'ذي', 'كيت', 'مما',
               'الذين', 'بعض', 'كذا', 'لك', 'أنتم', 'عسى', 'لستم', 'بهن',
               'هذي', 'ذواتا', 'بل', 'كأنما', 'إنه', 'لست', 'اللاتي', 'ذلكن',
               'كلا', 'كيف', 'لولا', 'من', 'إليك', 'ما', 'هاته', 'هاتي', 'سوف',
               'لستن', 'كأي', 'مع', 'منذ', 'هذين', 'لعل', 'هل', 'بكما', 'عدا',
               'كأين', 'هكذا', 'أكثر', 'كلما', 'أي', 'ليسوا', 'اللواتي',
               'حيثما', 'أف', 'اللائي', 'ليس', 'مه', 'أينما', 'إما', 'فإن',
               'هيا', 'إي', 'اللذين', 'أن', 'مذ', 'أولاء', 'ذا', 'كليكما',
               'والذي', 'ريث', 'تلكم', 'بهما', 'وإذا', 'اللتين', 'إليكما',
               'كي', 'كأن', 'كلتا', 'لاسيما', 'بي', 'آه', 'لكنما', 'لستما',
               'به', 'هاتين', 'إنما', 'تين', 'ومن', 'له', 'حيث', 'بهم', 'تلك',
               'أنت', 'أقل', 'حبذا', 'ذلك', 'فيم', 'بكن', 'ألا', 'لو', 'مهما',
               'بين', 'وما', 'عليه', 'فيما', 'أين', 'هنالك', 'التي', 'هيهات',
               'هذان', 'بلى', 'ذه', 'أو', 'ليسا', 'اللذان', 'أوه', 'ماذا',
               'لكي', 'عليك', 'ليستا', 'فيها', 'ها', 'كليهما', 'الذي', 'هنا',
               'ذاك', 'ذات', 'بها', 'بمن', 'آها', 'إليكم', 'ذوا', 'لهم',
               'ولا'},
    'azerbaijani': {'iyirmi', 'olar', 'oldu', 'onsuzda', 'idi', 'bunu', 'faiz',
                    'sənə', 'cı', 'yalnız', 'az', 'olmaz', 'da', 'özü', 'etmə',
                    'etmək', 'nə', 'qırx', 'bu', 'bəli', 'etdi', 'indi',
                    'yetmiş', 'doqsan', 'kimi', 'mənə', 'olmuşdur', 'artıq',
                    'görə', 'ci', 'sən', 'ə', 'biraz', 'mirşey', 'yoxdur',
                    'xan', 'həmişə', 'olaraq', 'yaxşı', 'beş', 'olan', 'olsun',
                    'səkkiz', 'ən', 'ad', 'buradan', 'of', 'il', 'cü', 'yüz',
                    'iki', 'ki', 'niyə', 'ilə', 'a', 'var', 'edən', 'ildə',
                    'olur', 'amma', 'bəlkə', 'kimə', 'buna', 'üçün', 'qarşı',
                    'sizin', 'xeyr', 'səhv', 'bilər', 'olduğu', 'onların ',
                    'oradan', 'bütün', 'düz', 'lap', 'arasında', 'gilə', 'öz',
                    'xanım', 'bəzi', 'yenə', 'bizlər', 'dəqiqə', 'otuz',
                    'əlbəttə', 'kim', 'isə', 'səksən', 'olmadı', 'doqquz',
                    'bəzən', 'onun', 'ondan', 'edir', 'istifadə', 'sənin',
                    'məhz', 'dörd', 'dedi', 'birşey', 'üç', 'ilk', 'cu', 'onu',
                    'bizim', 'deyil', 'hər', 'qədər', 'et', 'sadəcə', 'altı',
                    'daha', 'ay', 'dir', 'ı', 'təəssüf', 'on', 'bunların',
                    'haqqında', 'bundan', 'yeddi', 'onlardan', 'siz',
                    'əslində', 'yox', 'ha', 'bunun', 'harada', 'lakin', 'bəy',
                    'həm', 'çünki', 'bax', 'o', 'saat', 'hə', 'yəni', 'ona',
                    'bir', 'biri', 'biz', 'onlar', 'və', 'nəhayət', 'heç',
                    'in', 'elə', 'əlli', 'saniyə', 'çox', 'belə', 'sizlər',
                    'yoxsa', 'zaman', 'altmış', 'sonra', 'obirisi', 'ya',
                    'mən', 'əgər', 'də', 'dən', 'ü', 'dək', 'həmin'},
    'danish': {'blive', 'har', 'hans', 'mod', 'til', 'dig', 'din', 'da',
               'alle', 'nogle', 'under', 'ind', 'eller', 'dem', 'over',
               'bliver', 'den', 'sit', 'fra', 'når', 'vi', 'mit', 'som',
               'også', 'dette', 'end', 'nu', 'os', 'noget', 'jo', 'op', 'hvad',
               'en', 'skal', 'ned', 'man', 'efter', 'ad', 'sin', 'vor', 'selv',
               'hun', 'var', 'have', 'anden', 'du', 'her', 'hos', 'hvor',
               'skulle', 'at', 'jer', 'sine', 'mange', 'de', 'ham', 'havde',
               'mig', 'i', 'været', 'sig', 'være', 'mine', 'ud', 'jeg',
               'denne', 'ikke', 'et', 'dog', 'hvis', 'er', 'af', 'alt',
               'kunne', 'der', 'sådan', 'med', 'om', 'thi', 'hendes', 'min',
               'hende', 'disse', 'deres', 'vil', 'han', 'for', 'blev', 'det',
               'på', 'og', 'men', 'ville', 'meget'},
    'dutch': {'dus', 'altijd', 'onder', 'veel', 'bij', 'over', 'werd', 'me',
              'wil', 'voor', 'uw', 'haar', 'aan', 'van', 'tegen', 'zou', 'hij',
              'nu', 'met', 'op', 'reeds', 'en', 'zelf', 'of', 'hebben', 'doch',
              'dit', 'hier', 'een', 'niet', 'niets', 'hun', 'zich', 'iemand',
              'u', 'kan', 'iets', 'omdat', 'het', 'zal', 'waren', 'alles',
              'dat', 'ons', 'naar', 'de', 'want', 'die', 'toch', 'wezen',
              'maar', 'ja', 'kunnen', 'zonder', 'zij', 'door', 'eens', 'is',
              'mijn', 'doen', 'als', 'ge', 'na', 'er', 'kon', 'hoe', 'moet',
              'geen', 'uit', 'heeft', 'ook', 'toen', 'hem', 'al', 'der', 'ze',
              'andere', 'om', 'daar', 'nog', 'dan', 'zijn', 'deze', 'wordt',
              'ben', 'in', 'mij', 'was', 'te', 'tot', 'worden', 'heb', 'zo',
              'men', 'geweest', 'had', 'wat', 'ik', 'wie', 'meer', 'je'},
    'english': {'once', 'when', 'ain', 'an', 'after', 'most', 'ours', 'am',
                'theirs', 'any', 'him', 'here', "aren't", "hasn't", 'too',
                'himself', 'them', 'under', 'were', 'his', 'what', 'to',
                'these', 're', 'over', 'we', 'who', 'both', 'shan', 'all',
                'll', 'me', 'more', 'he', "don't", 'herself', 'against', 'has',
                'being', 'through', "you've", 'during', "shan't", 'she',
                "she's", 'hasn', 'themselves', 'mustn', "you're", "wasn't",
                'with', 'be', "should've", 'then', 'isn', "needn't", 'our',
                'where', "isn't", 'between', 'or', 'y', 'by', 'about', 'now',
                'couldn', 'does', "doesn't", 'of', "you'd", "it's", 'my',
                'from', 'its', 'a', 'having', 'have', 'her', 'doesn', 'other',
                'yours', 'but', 'up', 'each', 'because', 'myself', 'just',
                'so', 'it', 'above', 'don', 'few', 'off', 'aren', 'at',
                'should', 'further', 'not', 'below', 'only', 'yourselves',
                'doing', 'into', 'how', 'didn', 'won', 'which', 'and', 'will',
                'needn', 'i', 'your', "hadn't", 'than', "couldn't", 'weren',
                "haven't", 'very', 'is', "didn't", 'there', 'while', "you'll",
                'before', 'are', 'mightn', 's', 'the', "that'll", 'such',
                "mightn't", 'on', 'you', 'own', 'wasn', 'why', 'do', 'ma',
                'that', 'their', 'those', 'itself', "won't", 'been', 't',
                "shouldn't", 'again', 'o', 'if', 'm', 'nor', 'yourself', 'for',
                'd', 'in', 'haven', 'ourselves', 'was', 'can', "mustn't",
                'shouldn', 'until', 'wouldn', 'this', 'they', 'as', 'out',
                'hers', 'hadn', 've', 'had', 'no', 'whom', 'did', "wouldn't",
                'down', 'same', "weren't", 'some'},
    'finnish': {'sinua', 'joiksi', 'sinuun', 'minkä', 'minuun', 'mitä', 'kuka',
                'siihen', 'joiden', 'teitä', 'näiksi', 'noille', 'keiksi',
                'noita', 'sinulla', 'jonka', 'joissa', 'niissä', 'joilta',
                'sinä', 'me', 'noissa', 'he', 'tuolle', 'heistä', 'keille',
                'tähän', 'jota', 'olit', 'tässä', 'olisimme', 'noilta',
                'joille', 'johon', 'niistä', 'jolta', 'täksi', 'se', 'sillä',
                'sinut', 'tuohon', 'noin', 'emme', 'siltä', 'miksi', 'missä',
                'ovat', 'sinulle', 'niiksi', 'mikä', 'niitä', 'oli', 'olisin',
                'itse', 'ne', 'kenen', 'en', 'sinusta', 'olisit', 'mukaan',
                'joita', 'olemme', 'ette', 'noiden', 'heidän', 'keihin',
                'näistä', 'jolla', 'vaan', 'tuotä', 'niillä', 'heille',
                'siitä', 'sinulta', 'noista', 'joina', 'ketkä', 'noiksi',
                'vaikka', 'tämä', 'teillä', 'siinä', 'minun', 'meiltä',
                'näinä', 'kuin', 'heihin', 'nämä', 'joihin', 'tuossa',
                'hänelle', 'olisi', 'nuo', 'kenelle', 'meidät', 'hänet',
                'meihin', 'näille', 'olet', 'niiltä', 'minua', 'jos', 'olitte',
                'eivät', 'minulle', 'heissä', 'tältä', 'joilla', 'noilla',
                'jolle', 'minusta', 'heiltä', 'kenellä', 'jona', 'näihin',
                'hänen', 'tätä', 'keistä', 'ja', 'olla', 'joka', 'olisitte',
                'koska', 'meille', 'keneksi', 'heillä', 'olimme', 'ole',
                'meitä', 'tuona', 'mihin', 'mutta', 'sille', 'näillä',
                'tuoksi', 'minut', 'sen', 'josta', 'mistä', 'niiden', 'keiden',
                'teidän', 'keillä', 'tuon', 'heitä', 'noina', 'teiltä',
                'näissä', 'olivat', 'kanssa', 'et', 'tuolla', 'minulta',
                'noihin', 'sekä', 'teissä', 'niin', 'tälle', 'ollut', 'keitä',
                'tai', 'on', 'yli', 'heidät', 'sinun', 'keinä', 'niinä',
                'tallä', 'niihin', 'vai', 'että', 'tästä', 'olisivat', 'mitkä',
                'olen', 'ei', 'häneltä', 'jossa', 'keiltä', 'mille', 'näiltä',
                'tämän', 'kenenä', 'häneen', 'tuolta', 'hänellä', 'niille',
                'keneen', 'joksi', 'minussa', 'poikki', 'olleet', 'kenet',
                'hänestä', 'sitä', 'meidän', 'minulla', 'teistä', 'teille',
                'teihin', 'keneltä', 'kenessä', 'siksi', 'sinussa', 'joista',
                'tänä', 'olette', 'häntä', 'te', 'kun', 'millä', 'näitä',
                'jotka', 'hänessä', 'nyt', 'hän', 'meistä', 'teidät', 'näiden',
                'minä', 'kenestä', 'tuo', 'tuosta', 'miltä', 'meissä',
                'keissä', 'ketä', 'olin', 'meillä'},
    'german': {'ihren', 'mich', 'an', 'bin', 'zur', 'bis', 'andern', 'derer',
               'am', 'da', 'keine', 'hinter', 'alle', 'durch', 'denn', 'auch',
               'sein', 'warst', 'ein', 'jene', 'solches', 'dessen', 'des',
               'dem', 'anderes', 'demselben', 'unserem', 'ihr', 'solchem',
               'anderm', 'wir', 'einigem', 'den', 'manchem', 'zu', 'meines',
               'bei', 'desselben', 'sehr', 'allen', 'haben', 'jener',
               'dasselbe', 'mit', 'das', 'ihre', 'manchen', 'denselben',
               'deinem', 'wirst', 'werde', 'gegen', 'anderen', 'kein', 'hin',
               'sondern', 'dein', 'dann', 'dieser', 'dieses', 'ist', 'solchen',
               'auf', 'jedem', 'dich', 'einmal', 'man', 'derselben', 'doch',
               'muss', 'jenen', 'einiges', 'musste', 'seinen', 'hier',
               'selbst', 'uns', 'ihres', 'jenem', 'habe', 'um', 'unsere',
               'unseren', 'dass', 'euch', 'unseres', 'einige', 'jetzt', 'vor',
               'mein', 'sind', 'jenes', 'du', 'daß', 'dieselben', 'eure',
               'jeden', 'sie', 'einig', 'während', 'über', 'keines', 'einem',
               'mir', 'werden', 'manches', 'dies', 'nichts', 'noch', 'seine',
               'welchem', 'waren', 'wo', 'alles', 'ander', 'eines', 'so',
               'solche', 'anders', 'soll', 'war', 'deiner', 'hab', 'wollte',
               'nun', 'es', 'ihm', 'machen', 'die', 'können', 'zwischen',
               'allem', 'solcher', 'wird', 'nicht', 'indem', 'einer', 'will',
               'wieder', 'keinem', 'aber', 'sich', 'ihn', 'eurer', 'gewesen',
               'diese', 'sonst', 'nur', 'eine', 'könnte', 'seiner', 'aller',
               'ihnen', 'dort', 'euer', 'etwas', 'als', 'eures', 'dazu',
               'deine', 'er', 'ob', 'mancher', 'einiger', 'welcher', 'dir',
               'keiner', 'deinen', 'kann', 'hat', 'würde', 'hatten', 'einigen',
               'deines', 'meine', 'würden', 'meinem', 'derselbe', 'sollte',
               'damit', 'keinen', 'wollen', 'der', 'anderem', 'oder',
               'anderer', 'hatte', 'ich', 'bist', 'nach', 'ohne', 'andere',
               'jeder', 'seinem', 'ihrer', 'ihrem', 'also', 'diesem', 'weil',
               'welchen', 'und', 'weg', 'aus', 'seines', 'eurem', 'manche',
               'jedes', 'weiter', 'meinen', 'einen', 'für', 'anderr', 'viel',
               'in', 'meiner', 'jede', 'ins', 'dieselbe', 'unter', 'zwar',
               'von', 'was', 'diesen', 'wenn', 'zum', 'welche', 'welches',
               'vom', 'euren', 'unser', 'im', 'wie'},
    'greek': {'ειναι', 'οτι', 'ἄν', 'ὥστε', 'ὑπέρ', 'γα^', 'ταῖς', 'τῆσ',
              'ἀπὸ', 'ὅ', 'ἐὰν', 'οἳ', 'εκεινεσ', 'ποτε', 'τοτε', 'τὴν',
              'αλλα', 'μετά', 'τον', 'παρά', 'στον', 'ποιοσ', 'αὐτὸς', 'ἐμόσ',
              'μετ', 'οσο', 'τότε', 'οὐχὶ', 'ὑπό', 'εἰμί', 'σὺν', 'τοιοῦτος',
              'ἤ', 'ἐπεὶ', 'ὅς', 'οὕτως', 'ὅστις', 'μὴν', 'κατὰ', 'ὁ',
              'εκεινουσ', 'δαί', 'τι', 'ἄλλοσ', 'ὡσ', 'ὥς', 'κατά', 'ἐπὶ',
              'αυτοσ', 'αυτεσ', 'σε', 'εκεινα', 'κατ', 'οὐχ', 'ωσ', 'ἐστι',
              'αυτων', 'ὑπ', 'ᾧ', 'τα', 'ἀπό', 'ἔτι', 'ἐκ', 'τις', 'τά', 'αἳ',
              'ἣ', 'δαίσ', 'τήν', 'ὡς', 'καὶ', 'ὑπὲρ', 'τῆς', 'ποιοι', 'τίς',
              'οὗτοσ', 'τῇ', 'στο', 'οἱ', 'περί', "δι'", 'καίτοι', 'ομωσ',
              'τοί', 'δὴ', 'τινα', 'γοῦν', 'γε', 'περὶ', 'αυτο', 'στη', 'σὺ',
              'θα', 'και', 'οὕτωσ', 'ποια', 'παρ', 'σὸς', 'πρόσ', 'τησ', 'οὐ',
              'ἧς', 'πρὸ', 'κ', 'μα', 'ἑαυτοῦ', 'δε', 'ισωσ', 'μετὰ', 'οὐκ',
              'ἀπ', 'τοιοῦτοσ', 'εἰς', 'τοι', 'αυτα', 'οὐδείσ', 'οὐδεὶς', 'ἥ',
              'τοῖς', 'τοῦ', 'ἐπί', 'κατα', 'επ', 'εἰ', 'ποιων', 'ποιεσ', 'τό',
              'το', 'ὅσ', 'ειμαστε', 'τὸ', 'ὦ', 'ἃ', 'για', 'αυτουσ', 'οὐδὲν',
              'τε', 'αντι', 'ενω', 'δεν', 'τίσ', 'διὰ', 'ἂν', 'αἱ', 'οὗτος',
              'τὰς', 'τὸν', 'εἰσ', 'οὐδὲ', 'τισ', 'παρα', 'οὐδ', 'μὲν', 'οὕτω',
              'ὅπερ', 'ειστε', 'μέν', 'με', 'οὔτε', 'ὃς', "δ'", 'εκεινο',
              'προσ', 'να', 'ποῦ', 'που', 'κἀν', 'δέ', 'κι', 'οπωσ', 'ἄλλος',
              'ποιο', 'ἅμα', 'ὅστισ', 'δ’', 'επι', 'αἵ', 'η', 'μην', 'οὗ',
              'στην', 'αυτοι', 'ποιουσ', 'μη', 'ἀλλ’', 'ἐγώ', 'απο', 'γάρ',
              'ἀλλὰ', 'οὓς', 'ο', 'ἵνα', 'ἐν', 'οὖν', 'ὅδε', 'δή', 'ἐμὸς',
              'την', 'καθ', 'τοὺς', 'εἴμι', 'αὐτόσ', 'τί', 'διά', 'ἄρα', 'ὃ',
              'τῶν', 'παρὰ', 'ἢ', 'εκεινων', 'πωσ', 'ὅθεν', 'ὃν', 'πρὸς',
              'εκεινοι', 'σύν', 'καί', 'πως', 'των', 'αν', 'δαὶ', 'μή', 'μεθ',
              'τόν', 'ἀλλά', 'ἐξ', 'εἴτε', 'προ', 'ἐάν', 'ἀφ', 'μετα', 'ἐφ',
              'ὅτι', 'δὲ', 'οὐδέ', 'ειμαι', 'μὴ', 'σύ', 'δαὶς', 'μἐν', 'τῷ',
              'αὖ', 'γὰρ', 'εαν', 'εἰμὶ', 'μήτε', 'οἷς', 'ὑπὸ', 'εἴ', 'γα',
              'κἂν', 'οι', 'τούσ', 'ἡ', 'εισαι', 'σόσ', 'του', "ἀλλ'", 'αυτη',
              'ὑμόσ', 'ὅτε', 'ἐγὼ', 'τὰ', 'εκεινοσ', 'εκεινη'},
    'hungarian': {'vele', 'között', 'hiszen', 'meg', 'vagy', 'egyre', 'akik',
                  'most', 'elõtt', 'az', 'elõ', 'mint', 'fel', 'amolyan',
                  'cikkeket', 'egyéb', 'továbbá', 'valamint', 'ebben', 'kívül',
                  'csak', 'utána', 'szerint', 'jó', 'bár', 'õk', 'neki',
                  'mindig', 'nagyobb', 'és', 'hogy', 'amikor', 'mit',
                  'amelynek', 'õket', 'õ', 'nélkül', 'van', 'elsõ',
                  'keressünk', 'ellen', 'erre', 'cikkek', 'azon', 'pedig',
                  'sokkal', 'be', 'amelyekben', 'azután', 'amelyeket', 'még',
                  'vissza', 'talán', 'belül', 'ne', 'volna', 'azt', 'minden',
                  'amíg', 'lenne', 'ahhoz', 'legyen', 'tehát', 'amit', 'után',
                  'mindent', 'ki', 'össze', 'voltak', 'majd', 'új', 'voltam',
                  'ilyenkor', 'cikk', 'a', 'sem', 'annak', 'amelyek',
                  'azonban', 'alatt', 'azért', 'azzal', 'néha', 'néhány',
                  'lehetett', 'mellett', 'által', 'illetve', 'kell', 'úgy',
                  'mindenki', 'ison', 'maga', 'egyes', 'azok', 'ezzel', 'e',
                  'jól', 'ezt', 'legalább', 'ennek', 'mely', 'viszont',
                  'egyetlen', 'ezen', 'akkor', 'de', 'újra', 'volt', 'hanem',
                  'milyen', 'lenni', 'melyek', 'valami', 'több', 'utolsó',
                  'felé', 'ekkor', 'egész', 'nem', 'jobban', 'itt', 'saját',
                  'mintha', 'rá', 'egy', 'már', 'lesz', 'sokat', 'ahogy',
                  'olyan', 'elég', 'ilyen', 'át', 'voltunk', 'más', 'aki',
                  'egyik', 'valaki', 'mivel', 'semmi', 'mi', 'arról', 'ehhez',
                  'ahol', 'közül', 's', 'elõször', 'ill', 'így', 'lett', 'el',
                  'miért', 'persze', 'emilyen', 'ezek', 'sok', 'hogyan',
                  'nincs', 'nagyon', 'ismét', 'tovább', 'ott', 'ez', 'amely',
                  'abban', 'kellett', 'nekem', 'teljes', 'vagyok', 'igen',
                  'keresztül', 'aztán', 'mert', 'ami', 'míg', 'mikor',
                  'általában', 'szemben', 'nagy', 'vannak', 'ezért', 'való',
                  'újabb', 'számára', 'szinte', 'másik', 'én', 'ugyanis',
                  'vagyis', 'lehet', 'benne', 'arra', 'magát', 'éppen',
                  'amelyet', 'ill.', 'eddig'},
    'nepali': {'जसले', 'भित्री', 'बने', 'गरि', 'अर्थात', 'अन्तर्गत', 'सही',
               'कसैले', 'जसमा', 'गर्छु', 'उप', 'जस्तोसुकै', 'पर्याप्त',
               'बाहेक', 'भए', 'पहिलो', 'कृपया', 'सायद', 'सधै', 'सोही', 'आफ्नो',
               'संगै', 'रही', 'छू', 'पाँच', 'सम्भव', 'यसपछि', 'गरेका', 'पनि',
               'अर्थात्', 'तर', 'उदाहरण', 'वरीपरी', 'त', 'तिनी', 'आए',
               'राम्रो', 'नौ', 'एक', 'दिए', 'उनले', 'कसरी', 'यसो', 'आफ्नै',
               'राखे', 'तिर', 'तुरुन्तै', 'के', 'भन्दा', 'ती', 'माथि', 'बिशेष',
               'रूप', 'मात्र', 'गर्नु', 'गए', 'यस', 'अब', 'तिमी', 'आयो',
               'प्रति', 'बरु', 'को', 'बारे', 'थिएन', 'यस्तो', 'सारा', 'न',
               'जान', 'देखिन्छ', 'ओठ', 'यी', 'भएको', 'पहिल्यै', 'पर्थ्यो',
               'अर्को', 'साथ', 'गर्न', 'रहेका', 'भन', 'निम्ति', 'तिनिहरुलाई',
               'सो', 'क्रमशः', 'छैन', 'अक्सर', 'थियो', 'चार', 'दुई', 'हरे',
               'नत्र', 'गर्ने', 'गरेर', 'कहाँबाट', 'सक्छ', 'तिनीहरू', 'त्यहाँ',
               'कुरा', 'केही', 'वास्तवमा', 'उनको', 'पछि', 'दिनुहुन्छ', 'एकदम',
               'किनभने', 'जताततै', 'यसको', 'यसरी', 'यसबाहेक', 'सट्टा', 'लागि',
               'आजको', 'स्पष्ट', 'यो', 'तीन', 'समय', 'आफूलाई', 'हुन्', 'धेरै',
               'साँच्चै', 'नजिकै', 'पक्कै', 'जसको', 'कोही', 'चाहन्छु', 'पटक',
               'जब', 'पहिले', 'बीचमा', 'थिए', 'गरेको', 'तल', 'जुन', 'लाई',
               'जहाँ', 'तेस्रो', 'आफू', 'तपाई', 'निर्दिष्ट', 'छु', 'अगाडी',
               'किन', 'भन्छन्', 'पक्का', 'लगभग', 'गरौं', 'चाहनुहुन्छ', 'या',
               'तापनी', 'हुने', 'अन्यथा', 'गर्दै', 'सम्म', 'जसलाई', 'मेरो',
               'तिनीहरुको', 'तपाईको', 'प्लस', 'आदि', 'दिनुभएको', 'हो',
               'देखियो', 'पछिल्लो', 'यदि', 'भन्ने', 'एउटै', 'देखि', 'बीच',
               'चाले', 'मुख्य', 'त्यो', 'अझै', 'त्सैले', 'का', 'गयौ', 'देखे',
               'यथोचित', 'जबकि', 'तत्काल', 'सात', 'हुन', 'त्सपछि', 'छन्',
               'तदनुसार', 'म', 'गैर', 'तेस्कारण', 'सबैलाई', 'भन्नुभयो',
               'अरुलाई', 'चाहिए', 'हरेक', 'भने', 'भन्', 'ठीक', 'देखेर', 'जे',
               'शायद', 'यहाँ', 'कम से कम', 'कुनै', 'औं', 'गर्नुपर्छ', 'मलाई',
               'तथा', 'अन्य', 'पूर्व', 'मा', 'यति', 'नयाँ', 'उहालाई', 'पाँचौं',
               'भित्र', 'जस्तै', 'संग', 'नै', 'निम्नानुसार', 'प्रतेक', 'छौं',
               'अन्यत्र', 'बिरुद्ध', 'छ', 'अनुसार', 'अरु', 'देखेको', 'अलग',
               'नि', 'फेरी', 'राख्छ', 'कसै', 'साथै', 'बाहिर', 'पर्छ', 'जसबाट',
               'आत्म', 'दोस्रो', 'भर', 'यद्यपि', 'यहाँसम्म', 'सबै', 'रहेको',
               'कहिलेकाहीं', 'जस्तो', 'ले', 'जो', 'निम्न', 'गरी', 'हुन्छ',
               'कतै', 'र', 'जाहिर', 'गर्छ', 'कि', 'भन्छु'},
    'french': {'eux', 'moi', 'nos', 'aurait', 'ayants', 'fus', 'sur', 'mais',
               'seront', 'aurais', 'à', 'étée', 'auraient', 'avaient', 'des',
               'soit', 'j', 'eues', 'eûmes', 'tes', 'eussiez', 'me', 'que',
               'ayante', 'étiez', 'eusse', 'eussent', 'étés', 'serait', 'nous',
               'pas', 'eut', 'qu', 'vous', 'sois', 'eus', 'se', 'sa', 'sommes',
               'aurai', 'soyons', 'n', 'avait', 'ne', 'y', 'en', 'furent',
               'il', 'aurez', 'pour', 'avions', 'eût', 'avais', 'étant', 'mon',
               'la', 'du', 'les', 'votre', 'sont', 'fut', 'ses', 'fusse',
               'ayez', 'ces', 'même', 'serez', 'avez', 'étions', 'es',
               'auriez', 'fût', 'ait', 'de', 'était', 'ils', 'aient',
               'eussions', 'eue', 'serai', 'seriez', 'étaient', 'auras',
               'leur', 'ai', 'fûmes', 'eusses', 'suis', 'seras', 'êtes',
               'aura', 'aurons', 'fussiez', 'eûtes', 'eurent', 'toi', 'ayons',
               'ayant', 'un', 'par', 'et', 's', 'c', 'ayantes', 'seraient',
               'ce', 'ton', 'on', 'soyez', 'aux', 'fussent', 'aviez', 'serais',
               'aies', 'ma', 'notre', 'ta', 'serons', 'au', 'vos', 'l',
               'avons', 'sera', 'lui', 't', 'fûtes', 'elle', 'fussions',
               'étées', 'est', 'm', 'avec', 'soient', 'ont', 'dans', 'mes',
               'eu', 'étantes', 'd', 'étants', 'auront', 'aurions', 'te', 'ou',
               'été', 'son', 'le', 'as', 'étante', 'serions', 'une', 'fusses',
               'qui', 'aie', 'tu', 'étais', 'je'},
    'italian': {'sui', 'vostre', 'farei', 'su', 'tra', 'sugli', 'facessimo',
                'avete', 'da', 'facevamo', 'degl', 'ti', 'faccia', 'alle',
                'sia', 'farete', 'noi', 'perché', 'siano', 'fareste', 'mia',
                'stessimo', 'coi', 'facevo', 'all', 'sei', 'sulle', 'avrete',
                'nelle', 'fecero', 'sarete', 'quella', 'stessi', 'starò', 'vi',
                'dalle', 'nostre', 'voi', 'ci', 'nostro', 'fossero', 'chi',
                'facessero', 'stette', 'mio', 'vostra', 'quale', 'col',
                'quanto', 'avrei', 'fai', 'tutto', 'se', 'ebbi', 'dov',
                'degli', 'più', 'avendo', 'farò', 'fece', 'del', 'abbiate',
                'avevate', 'vostro', 'anche', 'stiano', 'ne', 'starai',
                'stavate', 'sta', 'nello', 'fui', 'ad', 'questo', 'sulla',
                'il', 'fummo', 'sto', 'facevi', 'stai', 'quante', 'faremo',
                'starete', 'agl', 'avrebbero', 'essendo', 'miei', 'sua',
                'facesse', 'stetti', 'negli', 'queste', 'farebbe', 'di',
                'facevano', 'a', 'ho', 'è', 'avevo', 'ed', 'aveva', 'la',
                'stavo', 'eri', 'stiate', 'ebbe', 'furono', 'questi',
                'faranno', 'siete', 'dallo', 'nei', 'facevate', 'che', 'dei',
                'erano', 'sareste', 'quanta', 'feci', 'stando', 'e', 'stavano',
                'siate', 'contro', 'dagl', 'abbia', 'una', 'faccio',
                'stessero', 'faresti', 'stanno', 'staremo', 'avevi', 'non',
                'stettero', 'della', 'faceva', 'stesti', 'abbiano', 'nostra',
                'tutti', 'abbiamo', 'faceste', 'avremo', 'sarebbero', 'starà',
                'tue', 'era', 'dell', 'avrebbe', 'delle', 'fossimo', 'stia',
                'i', 'avremmo', 'farai', 'staremmo', 'steste', 'staresti',
                'tuoi', 'eravate', 'farebbero', 'facessi', 'dove', 'dagli',
                'ai', 'dello', 'loro', 'starebbe', 'tua', 'facciamo', 'sue',
                'sarò', 'sarei', 'sugl', 'questa', 'mi', 'si', 'un', 'avemmo',
                'quelle', 'sull', 'siamo', 'c', 'faremmo', 'nel', 'suoi',
                'sarebbe', 'avranno', 'stemmo', 'stiamo', 'staranno', 'stava',
                'avresti', 'per', 'avrai', 'avessero', 'stareste', 'saremo',
                'stesse', 'fu', 'al', 'nella', 'dai', 'allo', 'dal', 'gli',
                'ma', 'avreste', 'dall', 'mie', 'ebbero', 'ha', 'avuti', 'sul',
                'foste', 'nostri', 'nell', 'suo', 'alla', 'avute', 'hanno',
                'fossi', 'facciate', 'negl', 'sarai', 'l', 'avrà', 'lui',
                'sono', 'o', 'facendo', 'starebbero', 'uno', 'li', 'avesse',
                'dalla', 'agli', 'io', 'in', 'lo', 'avevano', 'avuto', 'ero',
                'stavamo', 'con', 'cui', 'avrò', 'avevamo', 'eravamo',
                'saremmo', 'come', 'hai', 'facesti', 'fosti', 'le', 'quanti',
                'avuta', 'sarà', 'avessi', 'facciano', 'lei', 'avesti',
                'sullo', 'fanno', 'fosse', 'farà', 'facemmo', 'avessimo',
                'tuo', 'stavi', 'quello', 'vostri', 'saranno', 'quelli', 'tu',
                'saresti', 'starei', 'aveste'},
    'kazakh': {'сондай', 'сонымен', 'пай', 'өзге', 'жалт-жалт', 'әттеген-ай',
               'ол', 'кейбіреу', 'ешқандай', 'желп', 'онымен', 'әрине',
               'қалт-қалт', 'тыңқ', 'әні', 'алақай', 'ғұрлым', 'кәні',
               'әлдеқайдан', 'салым', 'құрау', 'бері', 'сізге', 'кәнеки',
               'саған', 'сенен\tонан', 'қатар', 'күңк', 'сыңқ', 'соң',
               'тарбаң-тарбаң', 'ғұрлы', 'олармен', 'әрбір', 'о', 'осылай',
               'тарта', 'мәссаған', 'туралы', 'шаңқ-шаңқ', 'ыңқ', 'әншейін',
               'әрне', 'сенімен', 'онда', 'өйткені', 'ох', 'ештеме', 'әрқалай',
               'астапыралла', 'ә', 'тағы', 'өз', 'бізбен', 'сіздердің',
               'сайын', 'кә', 'шіңк', 'әлдекім', 'арс', 'бойымен', 'сенің',
               'біздермен', 'дүңк', 'арс-ұрс', 'митың-митың', 'түге', 'тағыда',
               'па', 'я', 'ей', 'ешкім', 'еш', 'әлденеше', 'ау', 'пішә',
               'бүгжең-бүгжең', 'сіздермен', 'қыңқ', 'маңқ', 'ой', 'өзімнің',
               'эх', 'бар', 'сен', 'әлдене', 'тарс', 'әйткенмен', 'дәнеңе',
               'пай-пай', 'паһ-паһ', 'сияқты', 'менің', 'болп', 'ыржың-тыржың',
               'барлық', 'қош-қош', 'сенде', 'менде', 'дегенмен', 'морт',
               'таяу', 'маған', 'бірге', 'өзің', 'шаңқ-шұңқ', 'шақты', 'жалп',
               'анау', 'дейін', 'кәне', 'біздерден', 'ал', 'біреу',
               'сондықтан', 'түгел', 'қап', 'шырт', 'бізге', 'ешқайсы',
               'алдақашан', 'арбаң-арбаң', 'борт', 'оның', 'шәйт', 'бойы',
               'олардың', 'гүрс', 'қайсыбір', 'шек', 'осындай', 'ие', 'ана',
               'әйда', 'пфша', 'құрау-құрау', 'ғана', 'өй', 'осы', 'үйт',
               'сіз', 'бәрекелді', 'ешқашан', 'өзім', 'бізден', 'уай',
               'сіздерге', 'мына', 'олар', 'сізбен', 'мышы', 'қоса', 'дүрс',
               'алайда', 'біздердің', 'барша', 'қаңғыр-күңгір', 'арнайы',
               'мұндай', 'жуық', 'кейбір', 'бірнеше', 'өзі', 'моһ', 'япырмай',
               'тарс-тұрс', 'бұл', 'кәһ', 'далаң-далаң', 'гөрі', 'шіркін',
               'қайқаң-құйқаң', 'осынау', 'біздің', 'олардан',
               'арсалаң-арсалаң', 'қана', 'қаңқ-қаңқ', 'тәк',
               'ербелең-ербелең', 'күрт', 'қаңқ-құңқ', 'саңқ', 'біз', 'емес',
               'ырс', 'ешбір', 'уа', 'жалт-жұлт', 'бірдеме', 'мыңқ', 'сона',
               'әрқайсы', 'менен', 'таман', 'қаралы', 'беу', 'кейін', 'қарай',
               'күшім', 'шаңқ', 'біздерге', 'әттең', 'шейін', 'өзіме',
               'менімен', 'әй', 'тырс', 'себебі', 'күллі', 'алатау', 'бұндай',
               'міне', 'үшін', 'былп', 'мынау', 'бәрі', 'әркім', 'ура',
               'сарт-сұрт', 'жоқ', 'сіздерден', 'оһо', 'қалт-құлт', 'арқылы',
               'бүкіл', 'ырқ', 'айтпақшы', 'құр', 'сорап', 'батыр-бұтыр',
               'пырс', 'бетер', 'ах', 'одан', 'е', 'сіздер', 'сол',
               'әттегенай', 'масқарай', 'өзінің', 'өзіне', 'уау',
               'қызараң-қызараң', 'оларға', 'сенен', 'сіздің', 'эй', 'сонау',
               'пішту', 'қолп', 'ірк', 'әйтпесе', 'салаң-сұлаң', 'әлдеқалай',
               'әукім', 'солай', 'аһа', 'сарт', 'мен', 'ойпырмай', 'бұрын',
               'шамалы', 'қорс', 'бірақ', 'таңқ', 'сізден', 'барқ',
               'әлдеқашан', 'ай', 'жаракімалла', 'тек', 'біздер', 'кірт',
               'оған', 'бүйт'},
    'romanian': {'apoi', 'putini', 'ni', 'mod', 'vă', 'suntem', 'atare',
                 'câtva', 'noi', 'spre', 'aceşti', 'ăsta', 'va', 'ca', 'cîţi',
                 'mulţi', 'vreo', 'ului', 'atatea', 'ci', 'cît', 'intr', 'se',
                 'chiar', 'sa', 'acesta', 'unui', 'or', 'decit', 'avea', 'vor',
                 'oricât', 'ba', 'cîte', 'fara', 'unei', 'oricît', 'orice',
                 'fost', 'voastre', 'vreun', 'cineva', 'sunteţi', 'isi', 'iar',
                 'i', 'aţi', 'cîtva', 'şi', 'vostru', 'două', 'celor',
                 'ceilalti', 'el', 'pic', 'aceste', 'citi', 'fără', 'sa-mi',
                 'ei', 'atitea', 'parca', 'cele', 'undeva', 'această', 'lor',
                 'drept', 'aceea', 'nimic', 'astfel', 'voştri', 'altul',
                 'noştri', 'vom', 'oricine', 'pina', 'ceva', 'ul', 'acea',
                 'treia', 'atatia', 'oricând', 'fiţi', 'atunci', 'multi',
                 'voastră', 'deasupra', 'aici', 'său', 'acestea', 'fiecare',
                 'inainte', 'aş', 'unor', 'toţi', 'niste', 'sai', 'doilea',
                 'nou', 'poate', 'aceia', 'deci', 'cita', 'il', 'multa', 'îi',
                 'zi', 'patru', 'inapoi', 'după', 'prea', 'dat', 'eşti',
                 'totusi', 'de', 'mei', 'acel', 'avut', 'fata', 'abia', 'meu',
                 'foarte', 'alea', 'puţina', 'cînd', 'sint', 'mine', 'unul',
                 'cand', 'eram', 'până', 'ceea', 'unele', 'atita', 'acestia',
                 'alt', 'aveţi', 'ce', 'câte', 'ma', 'avem', 'mie', 'aia',
                 'ta', 'aceştia', 'ala', 'au', 'nici', 'lui', 't', 'ii',
                 'lângă', 'o', 'pe', 'tocmai', 'aceasta', 'li', 'doar', 'cit',
                 'vouă', 'câţi', 'ea', 'caruia', 'printr-', 'tot', 'ăştia',
                 'nişte', 'tu', 'cărui', 'ţi', 'incit', 'intre', 'despre',
                 'atata', 'mâine', 'da', 'citeva', 'fel', 'ale', 'căror',
                 'dintr', 'uneia', 'este', 'noastre', 'daca', 'ăla', 'noastră',
                 'astea', 'acestui', 'voi', 'altfel', 'oricînd', 'în', 'spate',
                 'unii', 'mai', 'iti', 'acela', 'toti', 'cumva', 'insa', 'ne',
                 'fii', 'noua', 'unu', 'treilea', 'lîngă', 'la', 'sau', 'u',
                 'toata', 'tăi', 'îmi', 'dintre', 'numai', 'una', 'anume',
                 'peste', 'fi', 'asa', 'pot', 'acest', 'era', 'doi', 'că',
                 'puţină', 'dată', 'totul', 'către', 'tale', 'primul', 'unora',
                 'mi', 'inca', 'prin', 'uneori', 'altcineva', 'catre', 'face',
                 'acelea', 'sale', 'atat', 'sintem', 'dă', 'mult', 'unuia',
                 'asupra', 'eu', 'in', 'cui', 'aceeasi', 'sunt', 'le', 'as',
                 'cite', 'sub', 'alti', 'atit', 'citiva', 'mă', 'oriunde',
                 'dintr-', 'care', 'din', 'am', 'aibă', 'ti', 'trei', 'altii',
                 'acelasi', 'ele', 'cind', 'unde', 'mîine', 'fim', 'ţie',
                 'pentru', 'mea', 'toată', 'vi', 'cei', 'ia', 'prima', 'ati',
                 'nu', 'acei', 'pai', 'dacă', 'totuşi', 'dupa', 'alta', 'nouă',
                 'atitia', 'ori', 'pînă', 'cât', 'sus', 'cum', 'a', 'sa-ti',
                 'îţi', 'să', 'tine', 'multe', 'e', 'ăstea', 'deja', 'puţin',
                 'căci', 'toate', 'cea', 'dar', 'zice', 'fie', 'carora', 'dau',
                 'cat', 'ai', 'cărei', 'nimeni', 'desi', 'cu', 'careia',
                 'tuturor', 'si', 'are', 'un', 'altceva', 'îl', 'tău',
                 'nostru', 'ălea', 'mele', 'v', 'oricare', 'multă', 'oricum',
                 'al', 'cine', 'cel', 'alte', 'adica', 'patra', 'nostri',
                 'imi', 'm', 'cam', 'fiu', 'acele', 'săi', 'deşi', 'te',
                 'acestei', 'asta', 'ar', 'mereu'},
    'indonesian': {'hendaklah', 'begitu', 'harus', 'lewat', 'betulkah',
                   'sesaat', 'sering', 'keluar', 'bertutur', 'dimaksudkan',
                   'tuturnya', 'disinilah', 'masing-masing', 'betul',
                   'sampai-sampai', 'atau', 'sesegera', 'cukuplah', 'sebegitu',
                   'mulanya', 'tutur', 'rupanya', 'maka', 'tapi', 'dahulu',
                   'termasuk', 'bolehkah', 'sejak', 'sesuatu', 'demi',
                   'diinginkan', 'akulah', 'dipersoalkan', 'kesampaian',
                   'bolehlah', 'kemungkinan', 'jelasnya', 'menjadi',
                   'diucapkan', 'enggaknya', 'tidakkah', 'jelaskan', 'bersiap',
                   'selalu', 'lagi', 'untuk', 'dilakukan', 'katakan',
                   'seketika', 'bisa', 'tentulah', 'nyatanya', 'se', 'maupun',
                   'mendatang', 'atas', 'baik', 'sementara', 'menyampaikan',
                   'dikatakannya', 'rata', 'dimulai', 'keseluruhannya', 'dua',
                   'menyatakan', 'inginkan', 'pun', 'bermacam', 'jika', 'soal',
                   'mengatakannya', 'sama', 'tertentu', 'mengungkapkan',
                   'mengira', 'supaya', 'selaku', 'sebuah', 'menghendaki',
                   'membuat', 'semampu', 'setelah', 'berapa', 'kan', 'mana',
                   'setibanya', 'akankah', 'melihatnya', 'sebelumnya',
                   'bermula', 'akan', 'berapapun', 'berdatangan', 'sampaikan',
                   'terdapat', 'memastikan', 'yaitu', 'sebanyak', 'diri',
                   'kapanpun', 'sendiri', 'menambahkan', 'mirip', 'terus',
                   'bung', 'tadi', 'serta', 'jawabnya', 'dekat', 'kenapa',
                   'ungkap', 'hal', 'sempat', 'tandasnya', 'sekalipun',
                   'saling', 'lima', 'tiap', 'hendaknya', 'sama-sama',
                   'begitupun', 'ataupun', 'ditunjuki', 'merasa', 'sebisanya',
                   'padanya', 'rasanya', 'kemudian', 'selanjutnya',
                   'dimaksudkannya', 'punya', 'tentunya', 'beberapa',
                   'ditambahkan', 'segalanya', 'disini', 'terutama', 'dulu',
                   'sepantasnyalah', 'dini', 'berjumlah', 'sekecil',
                   'beginilah', 'menyiapkan', 'sesudah', 'minta', 'sejauh',
                   'bulan', 'tanyakan', 'tersampaikan', 'diucapkannya',
                   'bagai', 'sambil', 'adanya', 'soalnya', 'dikatakan',
                   'walau', 'menunjuki', 'amatlah', 'bawah', 'siapapun',
                   'segera', 'kapan', 'saja', 'malahan', 'berakhirlah',
                   'karena', 'dan', 'mula', 'nantinya', 'mendatangkan',
                   'terjadilah', 'masih', 'dengan', 'berkali-kali', 'berkata',
                   'pasti', 'ditujukan', 'menuturkan', 'sebutnya', 'ucapnya',
                   'baru', 'dimulailah', 'tambahnya', 'kasus', 'mengibaratkan',
                   'dibuat', 'cara', 'manakala', 'sekadar', 'dijelaskan',
                   'sini', 'pentingnya', 'bila', 'manalagi', 'jelas', 'ini',
                   'nanti', 'melihat', 'mendatangi', 'hanyalah', 'kinilah',
                   'seseorang', 'ibarat', 'perlunya', 'selain', 'balik',
                   'seolah', 'menuju', 'mulailah', 'empat', 'mempergunakan',
                   'berkeinginan', 'aku', 'tertuju', 'melainkan', 'dikerjakan',
                   'diakhirinya', 'demikian', 'setiba', 'digunakan', 'dikira',
                   'memintakan', 'semata-mata', 'berturut-turut',
                   'diketahuinya', 'diperbuatnya', 'sekurang-kurangnya',
                   'kelihatannya', 'meskipun', 'seenaknya', 'menanya',
                   'dilalui', 'artinya', 'bagaimana', 'ibu', 'mengucapkan',
                   'dituturkan', 'cukupkah', 'memberikan', 'menegaskan',
                   'melalui', 'teringat-ingat', 'seluruh', 'dilihat',
                   'bertanya', 'boleh', 'dipergunakan', 'justru', 'makanya',
                   'bermaksud', 'sinilah', 'diingat', 'datang', 'ingin',
                   'pertama-tama', 'dong', 'nyaris', 'dijawab', 'bagaimanakah',
                   'memungkinkan', 'lah', 'menanti', 'secara', 'toh',
                   'mungkin', 'merupakan', 'kitalah', 'tidak', 'sebab',
                   'adapun', 'serupa', 'jikalau', 'tunjuk', 'buat', 'panjang',
                   'diantara', 'bahkan', 'dimisalkan', 'dirinya', 'misalnya',
                   'lain', 'perlukah', 'mengibaratkannya', 'biasa', 'caranya',
                   'kurang', 'begitukah', 'pertanyaan', 'waduh', 'terbanyak',
                   'jumlah', 'pada', 'sekitarnya', 'berlebihan', 'bapak',
                   'keseluruhan', 'bertanya-tanya', 'tidaklah', 'selamanya',
                   'memerlukan', 'bekerja', 'menunjukkan', 'sudahlah',
                   'antaranya', 'mengingat', 'didatangkan', 'demikianlah',
                   'olehnya', 'sewaktu', 'setinggi', 'jawaban', 'pastilah',
                   'pertama', 'cukup', 'walaupun', 'tampak', 'begitulah',
                   'diperkirakan', 'karenanya', 'mengatakan', 'menyebutkan',
                   'mampukah', 'dalam', 'pertanyakan', 'tegasnya', 'namun',
                   'sejenak', 'saya', 'katanya', 'selama-lamanya', 'melakukan',
                   'sehingga', 'bahwasanya', 'rasa', 'hingga', 'seterusnya',
                   'pula', 'ditanya', 'diketahui', 'ibaratkan', 'depan', 'per',
                   'sekalian', 'masihkah', 'wah', 'sedangkan', 'itulah',
                   'keduanya', 'tiba-tiba', 'haruslah', 'usah', 'misal',
                   'yakin', 'misalkan', 'tanya', 'percuma', 'dijelaskannya',
                   'diakhiri', 'gunakan', 'lanjutnya', 'berawal', 'saat',
                   'telah', 'kelima', 'mengakhiri', 'seluruhnya', 'ke', 'tiba',
                   'menanyakan', 'kemungkinannya', 'apakah', 'para',
                   'beginikah', 'berakhirnya', 'umum', 'lama', 'terasa',
                   'janganlah', 'secukupnya', 'terlihat', 'tanyanya',
                   'menjelaskan', 'kepada', 'turut', 'semaunya', 'siap',
                   'mengucapkannya', 'mempunyai', 'itukah', 'ketika',
                   'bermacam-macam', 'sekali-kali', 'tegas', 'memperlihatkan',
                   'berarti', 'bilakah', 'bukanlah', 'belakang', 'apabila',
                   'ditanyakan', 'siapa', 'memperkirakan', 'mempersiapkan',
                   'terakhir', 'paling', 'akhirnya', 'tanpa', 'sayalah',
                   'dialah', 'sebabnya', 'semula', 'benar', 'tadinya', 'waktu',
                   'berkenaan', 'kiranya', 'dimaksud', 'menyeluruh', 'meminta',
                   'bagi', 'luar', 'dipunyai', 'seperlunya', 'memulai',
                   'menunjuknya', 'mampu', 'sebagaimana', 'dipertanyakan',
                   'itu', 'diibaratkan', 'tetap', 'makin', 'jumlahnya',
                   'keadaan', 'berlangsung', 'terjadi', 'sebesar', 'semua',
                   'di', 'sepanjang', 'memang', 'berupa', 'dikarenakan',
                   'kapankah', 'sana', 'berbagai', 'sajalah', 'semuanya',
                   'hendak', 'bersama', 'dibuatnya', 'guna', 'malah',
                   'tampaknya', 'meski', 'semampunya', 'berikan', 'bagaikan',
                   'bukannya', 'sela', 'hari', 'enggak', 'ibaratnya',
                   'menurut', 'asalkan', 'semakin', 'tengah', 'sebaik-baiknya',
                   'ditunjuk', 'akhiri', 'belum', 'lebih', 'masalahnya', 'kok',
                   'benarlah', 'benarkah', 'jangan', 'juga', 'disebutkan',
                   'anda', 'nah', 'selama', 'ujarnya', 'ditunjukkannya',
                   'jawab', 'tiga', 'sepantasnya', 'kalian', 'sampai',
                   'sekiranya', 'apalagi', 'semasa', 'kira', 'sekurangnya',
                   'menandaskan', 'diberikannya', 'lalu', 'pak', 'seorang',
                   'sejumlah', 'sesuatunya', 'sudah', 'berada', 'pukul',
                   'berikutnya', 'seberapa', 'dimulainya', 'sedikitnya',
                   'semasih', 'terlebih', 'dimungkinkan', 'kita', 'daripada',
                   'mengenai', 'kembali', 'menggunakan', 'sekaligus', 'cuma',
                   'sebelum', 'hanya', 'pantas', 'adalah', 'mereka', 'pihak',
                   'ujar', 'tahu', 'kedua', 'seolah-olah', 'mempertanyakan',
                   'tetapi', 'padahal', 'kami', 'sendirian', 'disampaikan',
                   'teringat', 'ternyata', 'bukankah', 'pihaknya',
                   'meyakinkan', 'macam', 'bakalan', 'sendirinya', 'diberikan',
                   'berturut', 'disebutkannya', 'diperlihatkan', 'keinginan',
                   'belakangan', 'kalaupun', 'oleh', 'tersebut', 'diungkapkan',
                   'wong', 'entah', 'mengerjakan', 'begini', 'diingatkan',
                   'semata', 'dapat', 'ungkapnya', 'sebetulnya', 'persoalan',
                   'sebagai', 'terdahulu', 'terdiri', 'menanyai', 'ditegaskan',
                   'kepadanya', 'khususnya', 'yakni', 'kata', 'berakhir',
                   'menyangkut', 'diibaratkannya', 'sesudahnya', 'agak',
                   'bahwa', 'ikut', 'sebutlah', 'masing', 'diperbuat',
                   'mengetahui', 'jadinya', 'penting', 'seringnya', 'dimintai',
                   'berujar', 'berapalah', 'bisakah', 'sebaiknya', 'meyakini',
                   'jangankan', 'suatu', 'dituturkannya', 'antar',
                   'ditandaskan', 'siapakah', 'diantaranya', 'akhir', 'besar',
                   'dipastikan', 'sekarang', 'ia', 'entahlah', 'beginian',
                   'setempat', 'sebut', 'kelamaan', 'tandas', 'sesampai',
                   'katakanlah', 'kecil', 'amat', 'tentang', 'kamilah',
                   'agaknya', 'banyak', 'mendapatkan', 'diperlukan',
                   'keterlaluan', 'terlalu', 'ingat', 'dia', 'didapat',
                   'sebagainya', 'harusnya', 'agar', 'sudahkah', 'perlu',
                   'inginkah', 'waktunya', 'lanjut', 'biasanya', 'andalah',
                   'jadilah', 'kebetulan', 'sangat', 'mendapat', 'seusai',
                   'sedikit', 'masalah', 'mau', 'inikah', 'ingat-ingat',
                   'jadi', 'sekali', 'setiap', 'satu', 'memisalkan',
                   'sedemikian', 'sedang', 'bersama-sama', 'lamanya',
                   'kamulah', 'berkehendak', 'sepertinya', 'menginginkan',
                   'semisal', 'inilah', 'kini', 'lagian', 'menjawab',
                   'menunjuk', 'tak', 'pernah', 'sesekali', 'apa', 'berapakah',
                   'memperbuat', 'menanti-nanti', 'menaiki', 'jelaslah',
                   'bakal', 'seingat', 'hampir', 'sepihak', 'diminta',
                   'tempat', 'tepat', 'ucap', 'dari', 'ialah', 'mulai',
                   'sesama', 'terjadinya', 'apaan', 'mempersoalkan', 'umumnya',
                   'semisalnya', 'setengah', 'wahai', 'awal', 'mengingatkan',
                   'lainnya', 'memberi', 'sebaliknya', 'awalnya', 'disebut',
                   'kelihatan', 'mengapa', 'diberi', 'belumlah', 'tambah',
                   'kalau', 'saatnya', 'tahun', 'tinggi', 'mungkinkah',
                   'setidaknya', 'dimaksudnya', 'sebegini', 'tersebutlah',
                   'merekalah', 'ditunjuknya', 'ada', 'menantikan',
                   'sebenarnya', 'ataukah', 'kamu', 'memihak', 'jauh',
                   'bersiap-siap', 'sekadarnya', 'semacam', 'ditunjukkan',
                   'seharusnya', 'terhadapnya', 'berlalu', 'berlainan',
                   'sekitar', 'bukan', 'tentu', 'diperlukannya', 'kala',
                   'segala', 'sebagian', 'kira-kira', 'setidak-tidaknya',
                   'naik', 'terhadap', 'sebaik', 'bagaimanapun', 'berikut',
                   'ditanyai', 'yang', 'masa', 'terkira', 'antara', 'seperti',
                   'asal', 'bagian', 'beri', 'sangatlah', 'usai', 'kalaulah',
                   'apatah'},
    'portuguese': {'fôramos', 'estas', 'nos', 'pelo', 'dela', 'pelos',
                   'houveríamos', 'por', 'é', 'da', 'mais', 'houvemos', 'tem',
                   'à', 'às', 'teriam', 'como', 'ele', 'nossas', 'lhe', 'teus',
                   'estivéramos', 'delas', 'fomos', 'que', 'ao', 'me',
                   'houveremos', 'terei', 'nós', 'terá', 'formos', 'este',
                   'dele', 'isso', 'das', 'forem', 'tivéssemos', 'teríamos',
                   'estivéssemos', 'seria', 'estava', 'se', 'os',
                   'houvéssemos', 'houvermos', 'tivera', 'fui', 'tive', 'só',
                   'também', 'estivessem', 'foram', 'estivera', 'um', 'sua',
                   'qual', 'eles', 'estão', 'com', 'estavam', 'a', 'sem',
                   'tenha', 'hajam', 'estivemos', 'sejamos', 'tivermos',
                   'estejam', 'são', 'tuas', 'seríamos', 'vocês', 'uma',
                   'tinha', 'aqueles', 'houvera', 'havemos', 'e', 'fora',
                   'seu', 'terão', 'estivesse', 'seriam', 'minhas', 'éramos',
                   'houverão', 'tivéramos', 'aquele', 'estávamos', 'de',
                   'isto', 'serão', 'tiveram', 'mesmo', 'nas', 'haja', 'houve',
                   'nem', 'depois', 'ela', 'elas', 'somos', 'estes', 'fossem',
                   'estamos', 'meu', 'era', 'estejamos', 'houverei', 'seremos',
                   'teria', 'teremos', 'aos', 'tiverem', 'tivessem', 'num',
                   'em', 'aquilo', 'foi', 'tua', 'tivemos', 'esteja',
                   'estivermos', 'houverá', 'houverem', 'eram', 'deles', 'teu',
                   'houveria', 'lhes', 'esse', 'seus', 'houvessem', 'na',
                   'essas', 'estou', 'estiverem', 'serei', 'quem', 'muito',
                   'sejam', 'estive', 'entre', 'seja', 'já', 'pelas', 'aquela',
                   'tiver', 'está', 'até', 'esta', 'do', 'estiver',
                   'houveriam', 'hei', 'hão', 'esteve', 'tínhamos', 'tenhamos',
                   'nosso', 'tenho', 'numa', 'houvesse', 'houvéramos', 'essa',
                   'vos', 'fôssemos', 'temos', 'tinham', 'tém', 'será', 'o',
                   'suas', 'você', 'eu', 'for', 'não', 'nossos', 'esses',
                   'mas', 'minha', 'pela', 'quando', 'para', 'dos', 'te',
                   'estiveram', 'ou', 'hajamos', 'sou', 'as', 'houver',
                   'aquelas', 'tivesse', 'meus', 'no', 'fosse', 'teve', 'há',
                   'houveram', 'tenham', 'tu', 'nossa'},
    'swedish': {'har', 'hans', 'ni', 'vilket', 'ditt', 'vart', 'dig', 'din',
                'allt', 'för', 'mot', 'under', 'över', 'eller', 'dem', 'deras',
                'dina', 'den', 'här', 'sådana', 'hennes', 'henne', 'vi',
                'varje', 'när', 'vilka', 'inte', 'som', 'vara', 'nu', 'upp',
                'ingen', 'sina', 'kunde', 'så', 'en', 'detta', 'man', 'efter',
                'sin', 'då', 'inom', 'är', 'hade', 'var', 'du', 'kan', 'från',
                'blivit', 'skulle', 'där', 'ert', 'att', 'ett', 'blir', 'vid',
                'denna', 'varit', 'och', 'jag', 'dessa', 'de', 'vad', 'honom',
                'varför', 'mig', 'era', 'utan', 'i', 'ej', 'vars', 'sig',
                'någon', 'dess', 'själv', 'något', 'oss', 'sedan', 'er',
                'mycket', 'samma', 'sitta', 'vilken', 'några', 'sådan', 'vår',
                'ut', 'ha', 'med', 'hon', 'om', 'alla', 'till', 'än', 'min',
                'hur', 'mitt', 'ju', 'vem', 'vilkas', 'han', 'blev', 'mellan',
                'våra', 'sådant', 'det', 'icke', 'på', 'åt', 'men', 'bli',
                'mina', 'vårt', 'av'},
    'norwegian': {'hvilke', 'har', 'deira', 'hans', 'meg', 'til', 'ditt',
                  'vart', 'blei', 'inkje', 'din', 'sidan', 'da', 'varte',
                  'mot', 'alle', 'sia', 'ein', 'vors', 'eller', 'dem', 'bare',
                  'over', 'hva', 'me', 'den', 'opp', 'ble', 'fra', 'hennes',
                  'kvi', 'når', 'enn', 'vi', 'henne', 'medan', 'som', 'noen',
                  'eitt', 'også', 'dette', 'før', 'sitt', 'upp', 'hvorfor',
                  'ingen', 'hvem', 'så', 'somt', 'en', 'skal', 'ned', 'man',
                  'vere', 'deg', 'sin', 'ingi', 'dykkar', 'då', 'eit', 'um',
                  'hvordan', 'di', 'selv', 'hun', 'ho', 'blitt', 'var',
                  'hvilken', 'ikkje', 'dere', 'du', 'her', 'hadde', 'kan',
                  'hvor', 'mellom', 'hjå', 'kvifor', 'dei', 'nokre', 'mykje',
                  'nokon', 'skulle', 'somme', 'so', 'blir', 'ett', 'at',
                  'elles', 'vært', 'sine', 'mange', 'de', 'vort', 'begge',
                  'honom', 'deim', 'verte', 'siden', 'hennar', 'ja', 'i', 'nå',
                  'kva', 'inn', 'uten', 'være', 'etter', 'mine', 'jeg',
                  'denne', 'korleis', 'båe', 'noka', 'både', 'kven', 'ikke',
                  'si', 'mi', 'et', 'oss', 'samme', 'er', 'hvis', 'fordi',
                  'seg', 'hoe', 'korso', 'vore', 'å', 'hoss', 'dykk', 'kunne',
                  'kom', 'der', 'nokor', 'vår', 'ha', 'ut', 'med', 'sjøl',
                  'om', 'hossen', 'min', 'mitt', 'disse', 'deres', 'noe',
                  'deires', 'kvar', 'vil', 'han', 'for', 'kvarhelst', 'det',
                  'på', 'sånn', 'slik', 'og', 'kun', 'ved', 'inni', 'men',
                  'bli', 'noko', 'no', 'ville', 'hver', 'meget', 'eg', 'av'},
    'slovene': {'njenemu', 'ni', 'oba', 'mednju', 'drugega', 'petindvajseto',
                'stotero', 'enimi', 'nobeno', 'kdo', 'bojo', 'eni', 'dvojnim',
                'sedemnajste', 'deseterih', 'mora', 'čigar', 'desetemu',
                'šesto', 'želiva', 'dvojih', 'triintridesetih', 'onedve',
                'šestintridesetim', 'vsemi', 'tile', 'najinega', 'trojno',
                'štirinajstega', 'peter', 'kolikimi', 'trikratne',
                'petinosemdesetemu', 'peterih', 'šeste', 'vse', 'štiridesetem',
                'nočeva', 'enkratne', 'teboj', 'tisoča', 'osemdesetim',
                'le-tega', 'sto', 'šestintridesetimi', 'nečesa', 'katerih',
                'čigavega', 'drugačnem', 'nadme', 'svojo', 'desetere',
                'petinosemdesetima', 'dovoljen', 'dvojnih', 'petinosemdeseti',
                'dovolim', 'njegovo', 'sedemnajst', 'šestnajsta', 'štiristo',
                'dvoji', 'trinajstim', 'sedemindvajsete', 'štirinajstimi',
                'kakršenkoli', 'njihovih', 'trojnemu', 'okrog', 'vzdolž',
                'le-onega', 'njenim', 'od', 'drugačnemu', 'enaindvajsetega',
                'šeststotimi', 'teh', 'osemnajstega', 'enajstega',
                'sedemstotih', 'dobesedno', 'še', 'tolikšne',
                'enaintridesetim', 'sedemindvajsetim', 'dvaindevetdesetem',
                'dvojega', 'osemdesetem', 's', 'kolikšni', 'dovoljene',
                'dvakratne', 'le-takšno', 'oseminštiridesetimi', 'sabo',
                'prvim', 'ji', 'spričo', 'dvojnima', 'le-takšna', 'marsikom',
                'kogarkoli', 'njima', 'svoji', 'jih', 'moglo', 'česa',
                'takega', 'nikakršna', 'kakor', 'štirinajsto', 'osemnajstimi',
                'tristoti', 'takšnem', 'kakem', 'bila', 'hoteti',
                'sedemindvajsetemu', 'le-te', 'enajsti', 'tristote', 'njun',
                'katerimkoli', 'vsakih', 'naši', 'triindvajset', 'trojem',
                'čigavem', 'hočete', 'kakršnima', 'zmorejo', 'stoterem',
                'marsikaj', 'želele', 'petdesetim', 'me', 'sedemindvajsetem',
                'enako', 'menoj', 'petindevetdesetih', 'osmem',
                'dvaindevetdesetih', 'petintrideset', 'štirimi', 'katere',
                'morati', 'mojega', 'vaša', 'prvem', 'drugem', 'sedemsto',
                'najino', 'zmoremo', 'devetimi', 'vašimi', 'devetdesetimi',
                'sedmo', 'enaindvajsetemu', 'marsikatere', 'le-tako', 'vašega',
                'tolikimi', 'stotere', 'dvaindevetdeseti', 'nate',
                'devetintridesetih', 'onega', 'nobenem', 'petim', 'nobenima',
                'kolikšna', 'osemindevetdesetim', 'smo', 'drugačnima', 'smeti',
                'tebe', 'sedemindvajseta', 'sedemindvajset', 'mojih',
                'tretjem', 'komur', 'le-tistih', 'šestindvajsetih', 'mara',
                'isto', 'vendar', 'petem', 'štirinajstem', 'nekaki',
                'petindvajsetima', 'oseminštirideset', 'nekom', 'dvestota',
                'meni', 'njunih', 'svojemu', 'kake', 'tristotemu', 'takšna',
                'tisočerima', 'toliki', 'štiriindvajseta', 'petindvajsetem',
                'zmorem', 'vsem', 'stoterim', 'marsikaterim', 'predenj',
                'nekaterima', 'prvimi', 'petintridesetemu', 'enaindvajsetem',
                'desetero', 'šestintridesetih', 'jaz', 'želen', 'dvajsetim',
                'o', 'isti', 'triindvajseto', 'kakršnega',
                'petindevetdesetimi', 'šestnajstemu', 'čeravno',
                'kakršnemukoli', 'kolikšnem', 'tisočer', 'trojima', 'nekimi',
                'hotele', 'tisoči', 'vašo', 'osemnajste', 'marajva',
                'štiriindvajsetim', 'izpod', 'dvojno', 'devetnajstih',
                'njunem', 'zmogla', 'maralo', 'onidve', 'enkratni', 'vsaj',
                'nikakršen', 'petinsedemdesetih', 'osemdeseto', 'trojna',
                'enim', 'vrh', 'trojne', 'sedemindvajsetima', 'pete', 'h',
                'dvestote', 'vpričo', 'naš', 'vsaki', 'kakšna', 'trikratnima',
                'tolikšnemu', 'nekaterimi', 'druge', 'šestindvajset', 'ne',
                'en', 'kolikih', 'dvajsetimi', 'marsikatera', 'kakšno',
                'onstran', 'moči', 'katerem', 'hočejo', 'moje', 'maral',
                'petinštiridesetim', 'stotimi', 'njuna', 'ponje', 'drugačna',
                'trojnih', 'petinštirideseti', 'ista', 'čigavemu', 'njenimi',
                'kolikim', 'le-onima', 'tolikšni', 'vaše', 'našim',
                'šestdeset', 'najinimi', 'četrta', 'stotemu', 'vsakršnimi',
                'morda', 'vred', 'noben', 'takegale', 'marsikomu', 'njegovih',
                'desetim', 'onem', 'le-tisti', 'ponjo', 'petnajste', 'tale',
                'sedmemu', 'vsakršno', 'čimer', 'mi', 'njegovima', 'nad',
                'dovoliva', 'obenj', 'štiridesetemu', 'marveč', 'biti', 'ono',
                'nismo', 'petinsedemdesetim', 'takšnih', 'njihovo', 'on',
                'dovolijo', 'podnjo', 'kakršen', 'jim', 'osme',
                'triindvajsetega', 'le-tiste', 'osemnajsti', 'njihov',
                'le-tistega', 'sedme', 'nekakšnemu', 'enkratno', 'zmogle',
                'njihovimi', 'ponj', 'tudi', 'tistemu', 'njega', 'enakimi',
                'ju', 'tvojega', 'petindvajsetim', 'petdesetega', 'svoj',
                'nikakršnim', 'tisti', 'mano', 'stotega', 'ena', 'razen',
                'štirideset', 'štirideseto', 'marajta', 'kakšnega',
                'devetintridesetim', 'vanje', 'dvakratnimi', 'čeznje',
                'nekakšen', 'nekakih', 'štiristotih', 'devetnajsti', 'dvojnem',
                'sedemnajsto', 'maram', 'tri', 'njegovimi', 'devetstotimi',
                'zlasti', 'prvemu', 'takale', 'nadvse', 'tretjima', 'bodita',
                'desetimi', 'jo', 'nekemu', 'devetintridesetimi',
                'enaindvajseti', 'četudi', 'dvestotim', 'njenih',
                'petintridesetega', 'želela', 'moja', 'njenega', 'všeč',
                'vsakomur', 'moralo', 'nekima', 'trojnima', 'dvojimi',
                'tistima', 'proti', 'le-ona', 'neka', 'niti', 'dvajsetem',
                'zanjo', 'nanju', 'čigavim', 'nemara', 'zopet', 'nekatero',
                'tretjih', 'nekim', 'nam', 'svojimi', 'vsakršnih',
                'šestnajstima', 'tisočera', 'čim', 'kolikšen', 'tabo',
                'stoterima', 'le-tema', 'vajinima', 'sedmimi', 'nisem', 'radi',
                'devetdesetem', 'šestim', 'na', 'vsakršnega', 'petnajstim',
                'kakršnakoli', 'dovolila', 'enkratnim', 'v', 'petdeseta',
                'takšnega', 'nikakršno', 'dvojnega', 'trojni', 'takile', 'kak',
                'petintridesetim', 'le-takima', 'mojimi', 'vsemu', 'nekatera',
                'osem', 'najinem', 'njim', 'osmih', 'sedeminpetdesetih',
                'kakimi', 'najinima', 'namesto', 'drugemu', 'spet',
                'sedemdesetega', 'triinpetdesetih', 'katerega', 'čigavi',
                'dvojim', 'devetnajst', 'prvima', 'drugačne', 'enima',
                'nekaterih', 'tehle', 'dvojemu', 'česarkoli', 'izmed', 'vaju',
                'kakim', 'njene', 'maraš', 'tisočeremu', 'skozenj', 'njegovi',
                'sedmega', 'takem', 'tolikih', 'komurkoli', 'enkratnimi',
                'zase', 'triindvajsetem', 'trinajst', 'osemindevetdesetimi',
                'nekega', 'le-takšnega', 'bi', 'vame', 'dvaindevetdesetega',
                'nobena', 'bojda', 'šestdesetima', 'nekakega', 'želiš',
                'sedmima', 'želel', 'mojemu', 'nečem', 'dovoli', 'osemnajstih',
                'devetdesetih', 'čigavo', 'dvakratnem', 'rade', 'istih', 'po',
                'petintridesetih', 'marsikaterem', 'drugačni',
                'petinosemdesetimi', 'trije', 'naju', 'triinšestdesetimi',
                'temale', 'petinštiridesetem', 'bodimo', 'moreš', 'kakršnimi',
                'dvanajstega', 'kateremukoli', 'sedemstotimi', 'bili',
                'enkratnemu', 'najinim', 'tolikšno', 'dvanajstemu', 'osmimi',
                'šestih', 'tistimi', 'vsaka', 'tridesetima', 'kolikšnima',
                'svoje', 'svojem', 'nanj', 'enajstimi', 'tistem', 'nobenega',
                'marate', 'tistim', 'štiristotim', 'stote', 'petintridesetimi',
                'sedemnajstim', 'sicer', 'nekdo', 'ja', 'nadenj', 'nekakšnem',
                'svojih', 'petinštirideseto', 'četrtega', 'morejo', 'dovoliti',
                'smejo', 'njunimi', 'vajine', 'štiridesete',
                'štiriindvajsetih', 'vajinih', 'dvaindevetdeseta', 'komer',
                'katerihkoli', 'tolikšen', 'zmoreš', 'pote', 'hotimo',
                'štiriindvajsetega', 'pri', 'maramo', 'devetstotim', 'šeststo',
                'dvestoto', 'le-takšne', 'zmoreva', 'osemnajstim', 'zanj',
                'čem', 'takimale', 'ž', 'trojim', 'štirje', 'njen',
                'tolikšnima', 'nobene', 'ničemur', 'šestem', 'bodi', 'tisoč',
                'vsakršnim', 'triintridesetega', 'nekakšnim', 'šesta',
                'kakšen', 'dvanajste', 'deveto', 'navzlic', 'vaš', 'želena',
                'tristotim', 'tolikšnimi', 'nje', 'najinih', 'temle',
                'njegova', 'nihče', 'takšnimi', 'stotih', 'le-taka', 'tisočem',
                'petemu', 'sedemdesetem', 'triindvajsetih', 'njihove',
                'vašima', 'mnogo', 'dvaindevetdesetima', 'sedma', 'vaših',
                'kateremkoli', 'moraš', 'dvakratnega', 'vsakomer', 'enajstem',
                'naša', 'dvojni', 'temu', 'štiridesetih', 'trikratno', 'vanj',
                'temule', 'vam', 'zmogl', 'vsakršna', 'le-oni', 'njuno',
                'petinosemdeseto', 'našima', 'sedemnajsti', 'šesti', 'peteri',
                'čigava', 'sedmi', 'mojem', 'le-taki', 'trojemu',
                'sedemdeseta', 'nekaterim', 'njena', 'dvakraten', 'nekakim',
                'bodo', 'petega', 'njegove', 'našemu', 'le-tej', 'moremo',
                'kakršnimkoli', 'dvoja', 'kakemu', 'vsakim', 'njune', 'bržčas',
                'šestdesetimi', 'enaindvajsetima', 'želijo', 'one', 'kakšni',
                'kako', 'tretji', 'vama', 'dovolilo', 'kakršna', 'šestdesetih',
                'tvoj', 'šestindvajsetim', 'morajo', 'karkoli', 'nekaj',
                'temveč', 'hočemo', 'tisočere', 'le-takem', 'ničemer',
                'dvaindevetdesetimi', 'trikratnim', 'tridesetih',
                'osemindevetdesetih', 'čemurkoli', 'trinajstih',
                'triintrideseti', 'devetdeseta', 'triintrideseto', 'katero',
                'štirih', 'boste', 'petindevetdesetim', 'trinajstimi',
                'šestnajstimi', 'enega', 'sedeminpetdesetim', 'četrtimi',
                'nekako', 'pač', 'štiridesetega', 'gotovo', 'nekaka',
                'enkratnega', 'nadnje', 'trikratnih', 'drugačnim', 'neke',
                'istim', 'nikakršnemu', 'domala', 'petinosemdeseta', 'nočem',
                'marsikdo', 'sedemnajstima', 'takimle', 'taka', 'tisočim',
                'vaši', 'trinajsti', 'sedemdesetima', 'njihovima', 'tisočima',
                'da', 'trikratnem', 'kakršnih', 'trojimi', 'le-takšnim',
                'kakršnem', 'katerakoli', 'osemdesetemu', 'nerad', 'drugačen',
                'najinemu', 'toliko', 'kolikšnemu', 'onadva', 'kolikega',
                'nobenim', 'vajino', 'nikakršni', 'zanju', 'vsakega',
                'komerkoli', 'šestnajsti', 'vsakem', 'devet', 'devetim',
                'marajo', 'enajst', 'sedemstotim', 'petinštiridesetemu',
                'kakršnihkoli', 'izpred', 'našimi', 'devetega',
                'triindvajsetemu', 'kakršni', 'tristotega', 'štirideseti',
                'le-takšnima', 'dvojo', 'vajinim', 'marati', 'temuintemu',
                'kolikemu', 'dvaindevetdesete', 'njegovega', 'vajinega',
                'bržkone', 'sem', 'vate', 'njihova', 'devetnajsta',
                'petinosemdesetem', 'kakršnikoli', 'kakršnokoli', 'hočeta',
                'bodiva', 'osemnajstemu', 'zakaj', 'le-takšnih', 'vsakima',
                'tristotimi', 'tretjemu', 'tridesetemu', 'enake', 'enajstima',
                'štiriindvajsetimi', 'petdeset', 'kdorkoli',
                'petinštirideseta', 'enaindvajsetih', 'triintridesete',
                'le-ti', 'triindvajsetimi', 'kadar', 'želi', 'kolikšnimi',
                'sme', 'petindvajsete', 'kljub', 'nečim', 'petintrideseto',
                'osemdesetega', 'peterega', 'dvaindvajset', 'šestega',
                'osemdeset', 'dvaindvajsetih', 'dno', 'osemnajsta', 'verjetno',
                'dvojem', 'šestdesetemu', 'sedem', 'marsikaterih', 'kakšne',
                'vsakršni', 'tega', 'vajinem', 'peteremu', 'marsikateri',
                'tvojemu', 'nisva', 'rad', 'petinosemdesetega', 'bodisi',
                'zmoreta', 'petinosemdesetih', 'štirinajsta', 'zaradi',
                'šestima', 'devete', 'izven', 'tisočimi', 'triinšestdesetim',
                'nekakšne', 'triinšestdesetih', 'tebi', 'kolika',
                'štiriindvajset', 'istima', 'triintridesetimi', 'šestdesetem',
                'morete', 'taki', 'kar', 'sredi', 'dovoljena', 'petnajstima',
                'vase', 'njenem', 'petimi', 'ti', 'stoterega', 'nikakršne',
                'petdesetima', 'dvanajstima', 'moral', 'trinajstem', 'more',
                'hotite', 'enajstih', 'četrte', 'vi', 'blizu', 'komu',
                'kakršnim', 'petih', 'sedemnajstimi', 'nekakšna', 'neradi',
                'zapored', 'nekoliko', 'dve', 'tisto', 'dovoljeno',
                'devetstotih', 'enakemu', 'tolikšnim', 'mar', 'tisočo',
                'dovolita', 'petere', 'tolik', 'troje', 'šest', 'skozte',
                'čemerkoli', 'deseta', 'nekateri', 'mene', 'peto',
                'osemdesete', 'njuni', 'le-tistimi', 'petdesetih', 'tolikima',
                'čemer', 'štiridesetimi', 'enakih', 'morali',
                'sedemindvajsetimi', 'sedemnajstega', 'dvojnemu', 'nobenih',
                'petinpetdeset', 'štirideseta', 'kot', 'smeli', 'tvoja',
                'želeni', 'petnajstemu', 'dva', 'petnajstimi',
                'triintridesetim', 'stoterimi', 'marava', 'trojnem', 'najine',
                'kakšnem', 'samo', 'petima', 'med', 'štirinajstima', 'tretjo',
                'temi', 'nekem', 'le-takim', 'dvanajst', 'le-onem', 'čigavih',
                'nek', 'sedemnajstemu', 'naše', 'trikratnimi', 'triindvajseta',
                'njegovem', 'četrtima', 'takle', 'katerim', 'nekakimi',
                'čezenj', 'preden', 'tridesete', 'vsema', 'desetera',
                'šestemu', 'midva', 'šestnajstih', 'osmega', 'petinosemdesete',
                'trikratnemu', 'zoper', 'tisočega', 'le-one', 'drugačno',
                'predme', 'mojo', 'morava', 'petindvajseti', 'njeno',
                'le-tistemu', 'enakega', 'triinšestdeset', 'njegov', 'neki',
                'predvsem', 'trinajste', 'onkraj', 'jima', 'čigavimi',
                'sedeminpetdeset', 'pogodu', 'dovolili', 'se', 'devetdesetemu',
                'marsikatero', 'nočeš', 'kajti', 'triintridesetemu', 'tejle',
                'oziroma', 'nji', 'prvo', 'povrhu', 'katerikoli', 'enkratnima',
                'trojnega', 'štiriindvajsetem', 'bova', 'peti', 'dvajseto',
                'dvakratna', 'dvajsetemu', 'tisočerih', 'takšnemu', 'tvojim',
                'kolikšnega', 'tolikšna', 'devetdesete', 'takšne', 'drugim',
                'štiridesetim', 'nekakšnih', 'tolikšnega', 'tisočih',
                'kolikem', 'predse', 'nas', 'moreta', 'naokoli', 'kogar',
                'hoteli', 'petinštiridesete', 'onih', 'čez', 'dvajset',
                'želeli', 'mimo', 'nekakem', 'takemle', 'oseminštiridesetim',
                'trojo', 'vseh', 'petintridesetem', 'njih', 'njihovemu',
                'dvestoti', 'ona', 'le-tisto', 'kakršno', 'zgolj', 'celo',
                'dvakratnim', 'enaindvajsetimi', 'petindvajsetega', 'želita',
                'tristotem', 'kakršnemu', 'seboj', 'petnajsti', 'nekatere',
                'njimi', 'vsake', 'petinsedemdeset', 'dvakratni', 'želelo',
                'tretje', 'oseminštiridesetih', 'z', 'mogli', 'štirim',
                'moramo', 'morata', 'petnajsto', 'devetih', 'kakšnemu',
                'marsikoga', 'devetsto', 'marala', 'vajin',
                'sedeminšestdesetim', 'morate', 'enaindvajseto', 'nekakšnima',
                'šestdeseta', 'nekake', 'skorajda', 'dvanajstem', 'sta',
                'nekaterem', 'enem', 'osmo', 'zame', 'triindvajsetim', 'vsa',
                'nočemo', 'šestnajsto', 'devetnajstemu', 'smelo', 'petdesete',
                'ki', 'tvojih', 'njunima', 'deseterem', 'čigavima', 'k',
                'dvojima', 'nekakšnega', 'le-takšnemu', 'zavoljo', 'prvih',
                'drugačnimi', 'kolikšno', 'sedmim', 'nekakšno', 'marali',
                'vanjo', 'osmemu', 'osemdesetima', 'takole', 'nikakršnem',
                'šestdesetega', 'petinpetdesetimi', 'dvakratnemu',
                'petdesetimi', 'devetemu', 'šestdeseti', 'najini', 'čigave',
                'neko', 'vsak', 'devetdeseto', 'dvaindevetdeseto', 'nekakšni',
                'dvesto', 'enaintridesetimi', 'osemnajstem', 'štirinajstim',
                'želene', 'sedemindvajsetih', 'tolikšnem', 'take', 'kakršne',
                'vso', 'kom', 'dovolite', 'sva', 'za', 'le-tistim', 'ta',
                'drugih', 'marsikaterimi', 'hočeva', 'ga', 'trojnim',
                'tristoto', 'katerima', 'nobenemu', 'onimi', 'devetnajstem',
                'dvestotimi', 'dvema', 'bomo', 'tisočerimi', 'trinajstima',
                'mojima', 'desetima', 'osemdeseta', 'sedemindvajseto',
                'le-takšnimi', 'nečemu', 'hotita', 'petdeseti', 'petnajstih',
                'najina', 'trideseto', 'našega', 'izza', 'devetnajstima',
                'resda', 'zunaj', 'sedemnajstem', 'triindvajsete',
                'devetnajsto', 'enih', 'dvajseti', 'mu', 'petsto', 'trideseta',
                'štiristotimi', 'nikogar', 'dvojnimi', 'zmore', 'vas',
                'vašemu', 'desete', 'prve', 'nikar', 'petindvajseta', 'takele',
                'čemur', 'tretjimi', 'vendarle', 'njo', 'osemnajstima',
                'le-to', 'želimo', 'drugačnega', 'menda', 'medse', 'istem',
                'tolikem', 'petinštiridesetega', 'tridesetim', 'tolikemu',
                'pa', 'name', 'kajne', 'spod', 'svoja', 'tristo', 'prek',
                'takimile', 'deseteremu', 'trikraten', 'nočeta', 'tridesetega',
                'zmogli', 'želeti', 'petinosemdeset', 'šeststotim',
                'katerimakoli', 'enaki', 'drugačnih', 'kakih', 'hotel',
                'le-tem', 'nekak', 'desetih', 'bodite', 'četrtemu',
                'štiriindvajseti', 'moreva', 'šestnajstim', 'le-temu', 'tako',
                'petindvajsetimi', 'kakšnih', 'dvanajstih', 'enaindvajsetim',
                'tele', 'petstotim', 'eno', 'nikakršnimi', 'tvoji',
                'šestnajstem', 'le-takšen', 'tej', 'edinole', 'ravno',
                'dvestotemu', 'peta', 'kakima', 'navkljub', 'nekateremu',
                'dovolil', 'enaintrideset', 'hotelo', 'triinpetdeset',
                'devetnajstimi', 'le-temi', 'marsičim', 'enakima', 'le',
                'dvaindvajsetim', 'treh', 'vsakršnima', 'enajstemu', 'le-onih',
                'sedeminšestdeset', 'štiriindvajsete', 'če', 'čemu', 'to',
                'troji', 'naj', 'stoti', 'prvi', 'niso', 'četrti',
                'dvajsetega', 'kajpada', 'osmim', 'želeno', 'peterim',
                'najbrž', 'njihovi', 'ter', 'nekoga', 'drug', 'stoteri',
                'štiridesetima', 'enaindvajsete', 'trojega', 'iste', 'ničimer',
                'zmogel', 'dvainšestdesetim', 'hotela', 'dvanajsto',
                'njihovim', 'sploh', 'devetintrideset', 'stoto', 'petnajstega',
                'morem', 'enakem', 'bile', 'njemu', 'temile', 'tristotima',
                'osmi', 'kakršnemkoli', 'morale', 'osemdeseti', 'osma', 'saj',
                'dvestotima', 'tak', 'stotim', 'takihle', 'marsikateremu',
                'ene', 'kolike', 'smele', 'katerimikoli', 'trojnimi',
                'dvanajsti', 'le-tistima', 'petinštiridesetih',
                'petindvajsetemu', 'štirinajstih', 'štiri', 'kakršnimakoli',
                'osemdesetih', 'nama', 'skoznjo', 'marata', 'skoraj', 'si',
                'triinpetdesetim', 'marsikaterega', 'ko', 'smemo', 'poleg',
                'trinajsto', 'katerimi', 'troj', 'baje', 'vsej', 'osmima',
                'kaj', 'res', 'nase', 'prav', 'troja', 'petindevetdeset',
                'nobenimi', 'njeni', 'tema', 'nikakršnega', 'dvojna', 'drugi',
                'žal', 'dvanajsta', 'pome', 'njegovemu', 'devetnajste',
                'malone', 'vsakimi', 'smeš', 'sedeminpetdesetimi', 'takemu',
                'nikakršnima', 'dvojne', 'toda', 'dvajsetima', 'sebe',
                'sedeminšestdesetih', 'marsičem', 'kakega', 'hoče', 'tem',
                'odkar', 'mogle', 'nikakršnih', 'tisočero', 'trinajstega',
                'le-onemu', 'triintridesetima', 'koliki', 'prvega', 'deset',
                'petintridesetima', 'ampak', 'kakšnim', 'pet', 'četrto',
                'tvojo', 'kateremu', 'moj', 'katera', 'šele', 'kolik',
                'vsakemu', 'tristotih', 'smeta', 'trem', 'obeh', 'le-takega',
                'le-ono', 'petinštiridesetima', 'vidva', 'petstotih',
                'dvaindevetdesetim', 'nočete', 'itak', 'petstotimi', 'skoz',
                'namreč', 'devetdesetim', 'sedemnajsta', 'enakim', 'deseterim',
                'vsakršnemu', 'nekakšnimi', 'enajsta', 'okoli', 'trideset',
                'naših', 'le-take', 'do', 'njegovim', 'petintridesete',
                'tolikim', 'dvestotega', 'brez', 'smeva', 'deseteri',
                'devetnajstim', 'bil', 'hočeš', 'bo', 'kolikima', 'tretjega',
                'zadosti', 'četrtih', 'ste', 'sedeminšestdesetimi', 'morala',
                'tretjim', 'vsakršnem', 'krog', 'vsako', 'sedmih', 'deveta',
                'kolikšne', 'kakršnimikoli', 'je', 'njihovem', 'tridesetem',
                'peterimi', 'hoti', 'tiste', 'svojima', 'pred', 'takemule',
                'petinosemdesetim', 'dvestotih', 'triindvajsetima', 'nekakemu',
                'šeststotih', 'tvoje', 'nanjo', 'boš', 'devetdesetima',
                'tisoče', 'le-tak', 'želim', 'nekaterega', 'eden', 'smete',
                'precej', 'nista', 'niste', 'šestdesete', 'sedmem', 'tvojimi',
                'trikratnega', 'njenima', 'bosta', 'osemnajst', 'tolikšnih',
                'mojim', 'istega', 'kateri', 'tolike', 'obema', 'obe',
                'hotiva', 'vajinimi', 'koli', 'le-tistem', 'petintrideseta',
                'nami', 'že', 'marale', 'mogla', 'le-takšni', 'najsi',
                'nekomu', 'nič', 'skozi', 'drugimi', 'šestindvajsetimi', 'so',
                'dovolile', 'tistih', 'vštric', 'tegale', 'sebi',
                'petdesetemu', 'šestnajste', 'devetnajstega', 'sedemnajstih',
                'deseterima', 'druga', 'petdesetem', 'kdor', 'dvanajstimi',
                'enemu', 'trojih', 'nanje', 'prednje', 'dvaindevetdesetemu',
                'dvakratno', 'tridesetimi', 'stota', 'osemdesetimi', 'česar',
                'smela', 'čimerkoli', 'četrtem', 'drugima',
                'štiriindvajsetima', 'čigav', 'svojim', 'bom', 'nobeni', 'iz',
                'našem', 'svojega', 'tistega', 'kakršnekoli', 'zanje',
                'istemu', 'sedemdeseto', 'petnajsta', 'enkratnem', 'nikomer',
                'petera', 'vnovič', 'dvajsete', 'takšnim', 'vsi', 'vašim',
                'petinštirideset', 'le-takih', 'katerokoli', 'šestnajstega',
                'našo', 'petnajst', 'nikomur', 'šestimi', 'dvaindvajsetimi',
                'sedemdeseti', 'sedemindvajseti', 'trideseti', 'marsičemu',
                'torej', 'dvakratnima', 'devetdeseti', 'desetega', 'stotima',
                'tisočemu', 'preko', 'ničesar', 'tolikega', 'nisi', 'pod',
                'le-ta', 'zraven', 'trikratni', 'deseterega',
                'petinsedemdesetimi', 'marsičesa', 'ali', 'nočejo', 'dvoj',
                'le-teh', 'zmoči', 'tolika', 'kolikor', 'petnajstem',
                'vajinemu', 'dvojen', 'šestintrideset', 'dvakratnih', 'rada',
                'sedemdesetimi', 'smem', 'tole', 'dvajsetih', 'marsikaterima',
                'naproti', 'vašem', 'enkraten', 'iznad', 'enaintridesetih',
                'osemindevetdeset', 'petintrideseti', 'takimi', 'tremi',
                'mogel', 'peterem', 'le-takšnem', 'preprosto', 'njihovega',
                'kolikšnim', 'njem', 'deseto', 'drugo', 'petindvajset',
                'četrtim', 'onima', 'marajte', 'petinpetdesetih', 'kaka', 'ob',
                'trinajsta', 'enajsto', 'osemnajsto', 'deseter', 'želite',
                'enajstim', 'zate', 'devetem', 'koliko', 'štirinajsti',
                'štiriindvajsetemu', 'štirinajstemu', 'tvojima', 'le-onim',
                'vanju', 'moji', 'trojen', 'moram', 'tisočerim',
                'enaindvajset', 'le-takimi', 'najin', 'in', 'petindvajsetih',
                'dvestotem', 'tista', 'sedemdesete', 'vsega', 'enkratnih',
                'štirinajst', 'onim', 'njej', 'kajpak', 'šestdesetim', 'smel',
                'enajste', 'bilo', 'triintrideseta', 'takšno', 'vrhu',
                'njunemu', 'kateregakoli', 'raz', 'mednje', 'le-tista',
                'kakršnegakoli', 'takima', 'tretja', 'takih', 'vajini', 'dveh',
                'sedemdesetih', 'triindvajseti', 'dvainšestdesetih',
                'kolikšnih', 'šestdeseto', 'zares', 'dvajseta', 'tisočeri',
                'takšnima', 'sedemindvajsetega', 'tvojem', 'dvoje',
                'triinpetdesetimi', 'sedemdesetemu', 'tisočerem',
                'devetdesetega', 'enaindvajseta', 'vsakršne', 'kakšnima',
                'dovolimo', 'triintridesetem', 'enak', 'prva',
                'petinpetdesetim', 'enkratna', 'trikratna', 'vsakdo', 'njunim',
                'ker', 'kaki', 'noče', 'le-takemu', 'šestnajst', 'dvanajstim',
                'marajmo', 'dovoljeni', 'nekakima', 'morebiti', 'maraj',
                'seveda', 'stotera', 'takim', 'tisočerega', 'nekih', 'hočem',
                'deveti', 'desetem', 'vajina', 'čeprav', 'takšen', 'nasproti',
                'stoterih', 'kakšnimi', 'takšni', 'vami', 'enaka',
                'štirinajste', 'deseti', 'petero', 'le-toliko', 'devetima',
                'petinštiridesetimi', 'onemu', 'dvainšestdesetimi',
                'sedemdesetim', 'peterima', 'le-onimi', 'petdeseto',
                'vsakogar', 'zmorete', 'komaj', 'dvainšestdeset', 'stoteremu',
                'stoter', 'oni', 'njunega', 'deseterimi', 'stotem', 'koga',
                'katerekoli', 'devetdeset', 'pravzaprav', 'istimi', 'skoznje',
                'štiriindvajseto', 'dovoliš', 'ves', 'vsakršen', 'tristota',
                'te', 'povrh', 'sedemdeset', 'trinajstemu', 'njiju'},
    'russian': {'надо', 'ним', 'вас', 'один', 'где', 'нельзя', 'для', 'при',
                'будет', 'все', 'ему', 'чего', 'раз', 'он', 'себе', 'лучше',
                'ней', 'кто', 'этого', 'его', 'этом', 'о', 'или', 'они', 'мне',
                'всегда', 'когда', 'была', 'во', 'нас', 'никогда', 'чтоб',
                'есть', 'него', 'тем', 'эти', 'впрочем', 'меня', 'до', 'об',
                'я', 'ей', 'ли', 'их', 'три', 'мы', 'за', 'только', 'было',
                'не', 'больше', 'нибудь', 'тогда', 'сейчас', 'над', 'этот',
                'вам', 'совсем', 'чем', 'здесь', 'моя', 'какая', 'всю', 'был',
                'из', 'были', 'бы', 'куда', 'уже', 'такой', 'от', 'еще', 'тут',
                'ничего', 'у', 'вот', 'того', 'ж', 'иногда', 'им', 'какой',
                'наконец', 'на', 'что', 'перед', 'будто', 'ее', 'том', 'можно',
                'так', 'как', 'много', 'сам', 'опять', 'вы', 'вдруг', 'тоже',
                'но', 'а', 'два', 'под', 'потому', 'ну', 'со', 'теперь',
                'свою', 'да', 'более', 'ты', 'быть', 'если', 'после', 'всех',
                'без', 'них', 'про', 'может', 'мой', 'через', 'там', 'этой',
                'ведь', 'хоть', 'с', 'конечно', 'тот', 'по', 'даже', 'всего',
                'то', 'нее', 'чуть', 'почти', 'разве', 'эту', 'уж', 'тебя',
                'чтобы', 'между', 'она', 'другой', 'в', 'хорошо', 'и', 'нет',
                'себя', 'зачем', 'ни', 'к', 'же', 'потом'},
    'tajik': {'бояд', 'фақат', 'ғайри', 'болои ', 'ҳар қадар ки', 'шояд',
              'қабл', 'бай-бай', 'аз рӯи', 'ҳангоми', 'оббо', 'аз-баски ',
              'он', 'ҳаргиз', 'аз баҳри он ки', 'о', 'лекин', 'гар-чи', 'асло',
              'чанд', 'оё', 'балки', 'валекин ', 'вақте ки', 'гарчанде ки ',
              'лекин ва ҳол он ки', 'хайр', 'зеро', 'азбаски ', 'аст',
              'сар карда', 'даме ки', 'ором', 'чунки', 'ҳатто ки', 'нахот ки',
              'ва', 'ҳам', 'паси', 'ой', 'дида', 'барои он ки', 'не', 'бар',
              'ҳамон', 'бо', 'ҳм', 'пеш', 'ана ҳамин', 'ҳам ', 'уҳа', 'ҳамоно',
              'ҳмм', 'наход ки', 'баъд', 'аё', 'аз ', 'аҳа', 'модоме ки',
              'кошки ', 'танҳо', 'чӣ', 'агар чи', 'ана', 'тавба', 'ӯим ',
              'ҳо ана', 'эҳа', 'чунон ки', 'рӯ', 'бинобар', 'гӯё ки',
              'шояд ки', 'инҷониб', 'гар ', 'то ки', 'ё', 'то даме ки', 'ҷуз',
              'нм', 'ҳай-ҳай ', 'замон', 'на', 'аз рӯйи ', 'хом?ш', 'ҳарчанд',
              'бо вуҷуди он ки', 'охир', 'азбаски', 'чаро ки', 'вой-вой',
              'магар ', 'барои', 'оҳе', 'нахот', 'ки', 'ӯббо', 'э', 'агар-чи ',
              'ба', 'дар', 'назди', 'баъд аз он ки', 'мана', 'ту-ту', 'а',
              'аз', 'замоно', 'канӣ', 'ба шарте', 'бе он ки ', 'ар', 'гӯё',
              'эътиборан', 'то даме ки ', 'рӯйи', 'ҳой-ҳой ', 'ҳтимол',
              'бо нияти он ки', 'пеши', 'хуб ', 'мабодо', 'ваҳ', 'оре ', 'ҳа',
              'аҷабо', 'аз афташ', 'бинобар ин', 'агар ', 'то кӣ', 'агар ки',
              'то вақте ки', 'то', 'ало', 'кошкӣ', 'агар-чанд',
              'дар ҳолате ки', 'ҳатто ', 'ё ки', 'чун-ки', 'эҳ', 'зеро ки',
              'хуш', 'аммо', 'ҳу', 'ӯ', 'наход', 'ҳой', 'ӯҳӯ', 'бале ', 'ҷо',
              'ҳе', 'майлаш куя', 'бе', 'ин', 'ё ин ки  ', 'и', 'агар',
              'кадом', 'вале', 'на ин ки', 'ҳар', 'ба тразе ки '},
    'turkish': {'siz', 'de', 'hem', 'tüm', 'veya', 'ne', 'ise', 'belki', 'en',
                'az', 'da', 'sanki', 'kim', 'ki', 'mü', 'bu', 'ile', 'niçin',
                'hiç', 'acaba', 'nerede', 'o', 'diye', 'nereye', 'biz', 'biri',
                'için', 'şey', 'birşey', 'mı', 'her', 'hepsi', 'nerde',
                'nasıl', 'gibi', 'hep', 'defa', 'bazı', 'mu', 'birkaç', 'çok',
                'eğer', 'ya', 'kez', 'ama', 've', 'aslında', 'niye', 'daha',
                'yani', 'neden', 'şu', 'çünkü'},
    'spanish': {'ni', 'estuviésemos', 'su', 'tienes', 'unos', 'como',
                'estuvieseis', 'he', 'hubiesen', 'estarán', 'sentid',
                'habríamos', 'sentidas', 'hubierais', 'hubieses', 'se',
                'serían', 'habido', 'nuestras', 'tengáis', 'desde', 'nada',
                'estad', 'ellos', 'sobre', 'estuviesen', 'estar', 'estaríamos',
                'habréis', 'vosotros', 'estaban', 'éramos', 'es', 'habidas',
                'hubisteis', 'habían', 'durante', 'algunas', 'fueseis',
                'tendré', 'están', 'nosotros', 'tuvieses', 'el', 'hube', 'mí',
                'estos', 'esta', 'cual', 'tuyo', 'estáis', 'erais', 'algo',
                'estuvimos', 'fuisteis', 'tuvo', 'donde', 'tuvieseis',
                'tuvierais', 'estarías', 'tendría', 'otra', 'hemos',
                'tuviesen', 'vuestro', 'estemos', 'ya', 'seáis', 'tenido',
                'vuestra', 'hubieras', 'nos', 'esas', 'estadas', 'estarás',
                'estarían', 'seríais', 'me', 'tenga', 'has', 'tengo', 'tenía',
                'tuviese', 'suyas', 'tuviésemos', 'tendrá', 'estaréis',
                'estará', 'sin', 'poco', 'tendremos', 'nuestro', 'eso',
                'tuyas', 'tuvieron', 'tengamos', 'tuve', 'mis', 'teniendo',
                'habré', 'estaba', 'mías', 'de', 'estaríais', 'tuya', 'soy',
                'somos', 'había', 'habida', 'nosotras', 'míos', 'tengan',
                'tendrían', 'sea', 'tenidas', 'habrá', 'está', 'fuimos',
                'fuiste', 'hubiste', 'teníais', 'fuerais', 'nuestros',
                'estuvieron', 'tengas', 'o', 'tendrán', 'eran', 'estabas',
                'serán', 'con', 'para', 'teníamos', 'no', 'tu', 'vosotras',
                'habría', 'tened', 'suyos', 'habremos', 'tanto', 'habrán',
                'mía', 'habríais', 'habiendo', 'cuando', 'otros', 'suyo',
                'este', 'estás', 'estoy', 'siente', 'fuesen', 'tuvieras', 'os',
                'estuviste', 'seas', 'qué', 'tendríamos', 'y', 'en', 'estados',
                'fui', 'hubieseis', 'habíais', 'estaremos', 'seamos', 'tiene',
                'la', 'fuésemos', 'fueses', 'esos', 'estén', 'hubieron',
                'tendríais', 'una', 'algunos', 'tendréis', 'tenían', 'hubiese',
                'estamos', 'sí', 'quienes', 'hubieran', 'era', 'esa',
                'hubimos', 'fuese', 'ella', 'fueron', 'serás', 'sentida',
                'los', 'mi', 'estuvo', 'estada', 'habías', 'estabais', 'muy',
                'fue', 'habidos', 'entre', 'las', 'tuviera', 'eras', 'serías',
                'estábamos', 'mucho', 'ha', 'tus', 'hubiera', 'pero',
                'sentidos', 'tuvieran', 'ese', 'será', 'ellas', 'uno',
                'sintiendo', 'tenemos', 'eres', 'fueran', 'tenidos', 'todo',
                'tuviéramos', 'son', 'le', 'antes', 'tenéis', 'estuvieses',
                'tuvimos', 'estaría', 'estas', 'estuvieras', 'por', 'quien',
                'ti', 'hayas', 'suya', 'tenías', 'estuviera', 'esté', 'estaré',
                'hubiéramos', 'que', 'estuviese', 'sean', 'sois', 'hayamos',
                'tuviste', 'del', 'él', 'estés', 'seréis', 'porque', 'sus',
                'nuestra', 'fuera', 'estado', 'tú', 'a', 'estando', 'haya',
                'sería', 'les', 'seríamos', 'hubo', 'hayan', 'habéis', 'e',
                'estuve', 'hay', 'estuvieran', 'todos', 'hubiésemos', 'fueras',
                'tuvisteis', 'vuestros', 'seremos', 'ante', 'otras',
                'fuéramos', 'estuvierais', 'habíamos', 'hayáis', 'más',
                'estéis', 'un', 'habrías', 'esto', 'mío', 'otro', 'contra',
                'tendrás', 'habrás', 'al', 'yo', 'muchos', 'sentido',
                'tendrías', 'seré', 'tienen', 'estuvisteis', 'vuestras', 'han',
                'tenida', 'hasta', 'estuviéramos', 'lo', 'te', 'habrían',
                'también', 'tuyos'}}


_lang_map = {
    'ar': 'arabic',
    'az': 'azerbaijani',
    'da': 'danish',
    'nl': 'dutch',
    'en': 'english',
    'fi': 'finnish',
    'de': 'german',
    'el': 'greek',
    'hu': 'hungarian',
    'ne': 'nepali',
    'fr': 'french',
    'it': 'italian',
    'ro': 'romanian',
    'id': 'indonesian',
    'pt': 'portuguese',
    'sv': 'swedish',
    'nn': 'norwegian',
    'nb': 'norwegian',
    'sl': 'slovene',
    'ru': 'russian',
    'tg': 'tajik',
    'tr': 'turkish',
    'es': 'spanish',
}


def get_words(languages=None):
    all_words = set()
    for lang, word_set in _words.items():
        if languages and lang not in languages:
            continue
        all_words |= word_set
    return all_words
